package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArticulosXPuntoVentaId generated by hbm2java
 */
@Embeddable
public class ArticulosXPuntoVentaId implements java.io.Serializable {

	private int idPuntoVenta;
	private int idArticulo;

	public ArticulosXPuntoVentaId() {
	}

	public ArticulosXPuntoVentaId(int idPuntoVenta, int idArticulo) {
		this.idPuntoVenta = idPuntoVenta;
		this.idArticulo = idArticulo;
	}

	@Column(name = "id_punto_venta", nullable = false)
	public int getIdPuntoVenta() {
		return this.idPuntoVenta;
	}

	public void setIdPuntoVenta(int idPuntoVenta) {
		this.idPuntoVenta = idPuntoVenta;
	}

	@Column(name = "id_articulo", nullable = false)
	public int getIdArticulo() {
		return this.idArticulo;
	}

	public void setIdArticulo(int idArticulo) {
		this.idArticulo = idArticulo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArticulosXPuntoVentaId))
			return false;
		ArticulosXPuntoVentaId castOther = (ArticulosXPuntoVentaId) other;

		return (this.getIdPuntoVenta() == castOther.getIdPuntoVenta())
				&& (this.getIdArticulo() == castOther.getIdArticulo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPuntoVenta();
		result = 37 * result + this.getIdArticulo();
		return result;
	}

}
