package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ArticulosXProducto generated by hbm2java
 */
@Entity
@Table(name = "articulos_x_producto", catalog = "muvitul")
public class ArticulosXProducto implements java.io.Serializable {

	private ArticulosXProductoId id;
	private Articulo articulo;
	private Producto producto;
	private long cantidad;

	public ArticulosXProducto() {
	}

	public ArticulosXProducto(ArticulosXProductoId id, Articulo articulo, Producto producto, long cantidad) {
		this.id = id;
		this.articulo = articulo;
		this.producto = producto;
		this.cantidad = cantidad;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idProducto", column = @Column(name = "id_producto", nullable = false)),
			@AttributeOverride(name = "idArticulo", column = @Column(name = "id_articulo", nullable = false)) })
	public ArticulosXProductoId getId() {
		return this.id;
	}

	public void setId(ArticulosXProductoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_articulo", nullable = false, insertable = false, updatable = false)
	public Articulo getArticulo() {
		return this.articulo;
	}

	public void setArticulo(Articulo articulo) {
		this.articulo = articulo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_producto", nullable = false, insertable = false, updatable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "cantidad", nullable = false)
	public long getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(long cantidad) {
		this.cantidad = cantidad;
	}

}
