package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ArticulosXPuntoVenta generated by hbm2java
 */
@Entity
@Table(name = "articulos_x_punto_venta", catalog = "muvitul")
public class ArticulosXPuntoVenta implements java.io.Serializable {

	private ArticulosXPuntoVentaId id;
	private Articulo articulo;
	private PuntoVenta puntoVenta;

	public ArticulosXPuntoVenta() {
	}

	public ArticulosXPuntoVenta(ArticulosXPuntoVentaId id, Articulo articulo, PuntoVenta puntoVenta) {
		this.id = id;
		this.articulo = articulo;
		this.puntoVenta = puntoVenta;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idPuntoVenta", column = @Column(name = "id_punto_venta", nullable = false)),
			@AttributeOverride(name = "idArticulo", column = @Column(name = "id_articulo", nullable = false)) })
	public ArticulosXPuntoVentaId getId() {
		return this.id;
	}

	public void setId(ArticulosXPuntoVentaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_articulo", nullable = false, insertable = false, updatable = false)
	public Articulo getArticulo() {
		return this.articulo;
	}

	public void setArticulo(Articulo articulo) {
		this.articulo = articulo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_punto_venta", nullable = false, insertable = false, updatable = false)
	public PuntoVenta getPuntoVenta() {
		return this.puntoVenta;
	}

	public void setPuntoVenta(PuntoVenta puntoVenta) {
		this.puntoVenta = puntoVenta;
	}

}
