package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AuditoriaConfigAtributo generated by hbm2java
 */
@Entity
@Table(name = "auditoria_config_atributo", catalog = "muvitul")
public class AuditoriaConfigAtributo implements java.io.Serializable {

	private int idAtributo;
	private AuditoriaConfigMetodo auditoriaConfigMetodo;
	private int indice;
	private String clase;
	private Date fechaModificacion;
	private Set<AuditoriaConfigExpresion> auditoriaConfigExpresions = new HashSet<AuditoriaConfigExpresion>(0);

	public AuditoriaConfigAtributo() {
	}

	public AuditoriaConfigAtributo(int idAtributo, AuditoriaConfigMetodo auditoriaConfigMetodo, int indice,
			String clase, Date fechaModificacion) {
		this.idAtributo = idAtributo;
		this.auditoriaConfigMetodo = auditoriaConfigMetodo;
		this.indice = indice;
		this.clase = clase;
		this.fechaModificacion = fechaModificacion;
	}

	public AuditoriaConfigAtributo(int idAtributo, AuditoriaConfigMetodo auditoriaConfigMetodo, int indice,
			String clase, Date fechaModificacion, Set<AuditoriaConfigExpresion> auditoriaConfigExpresions) {
		this.idAtributo = idAtributo;
		this.auditoriaConfigMetodo = auditoriaConfigMetodo;
		this.indice = indice;
		this.clase = clase;
		this.fechaModificacion = fechaModificacion;
		this.auditoriaConfigExpresions = auditoriaConfigExpresions;
	}

	@Id

	@Column(name = "id_atributo", unique = true, nullable = false)
	public int getIdAtributo() {
		return this.idAtributo;
	}

	public void setIdAtributo(int idAtributo) {
		this.idAtributo = idAtributo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_metodo", nullable = false)
	public AuditoriaConfigMetodo getAuditoriaConfigMetodo() {
		return this.auditoriaConfigMetodo;
	}

	public void setAuditoriaConfigMetodo(AuditoriaConfigMetodo auditoriaConfigMetodo) {
		this.auditoriaConfigMetodo = auditoriaConfigMetodo;
	}

	@Column(name = "indice", nullable = false)
	public int getIndice() {
		return this.indice;
	}

	public void setIndice(int indice) {
		this.indice = indice;
	}

	@Column(name = "clase", nullable = false, length = 200)
	public String getClase() {
		return this.clase;
	}

	public void setClase(String clase) {
		this.clase = clase;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", nullable = false, length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "auditoriaConfigAtributo")
	public Set<AuditoriaConfigExpresion> getAuditoriaConfigExpresions() {
		return this.auditoriaConfigExpresions;
	}

	public void setAuditoriaConfigExpresions(Set<AuditoriaConfigExpresion> auditoriaConfigExpresions) {
		this.auditoriaConfigExpresions = auditoriaConfigExpresions;
	}

}
