package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AuditoriaObjeto generated by hbm2java
 */
@Entity
@Table(name = "auditoria_objeto", catalog = "muvitul")
public class AuditoriaObjeto implements java.io.Serializable {

	private Integer idBitacora;
	private int idMetodo;
	private Date fecha;
	private int idUsuario;
	private int idEvento;
	private AuditoriaAtributoObjeto auditoriaAtributoObjeto;

	public AuditoriaObjeto() {
	}

	public AuditoriaObjeto(int idMetodo, Date fecha, int idUsuario, int idEvento) {
		this.idMetodo = idMetodo;
		this.fecha = fecha;
		this.idUsuario = idUsuario;
		this.idEvento = idEvento;
	}

	public AuditoriaObjeto(int idMetodo, Date fecha, int idUsuario, int idEvento,
			AuditoriaAtributoObjeto auditoriaAtributoObjeto) {
		this.idMetodo = idMetodo;
		this.fecha = fecha;
		this.idUsuario = idUsuario;
		this.idEvento = idEvento;
		this.auditoriaAtributoObjeto = auditoriaAtributoObjeto;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_bitacora", unique = true, nullable = false)
	public Integer getIdBitacora() {
		return this.idBitacora;
	}

	public void setIdBitacora(Integer idBitacora) {
		this.idBitacora = idBitacora;
	}

	@Column(name = "id_metodo", nullable = false)
	public int getIdMetodo() {
		return this.idMetodo;
	}

	public void setIdMetodo(int idMetodo) {
		this.idMetodo = idMetodo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "id_usuario", nullable = false)
	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "id_evento", nullable = false)
	public int getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(int idEvento) {
		this.idEvento = idEvento;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "auditoriaObjeto")
	public AuditoriaAtributoObjeto getAuditoriaAtributoObjeto() {
		return this.auditoriaAtributoObjeto;
	}

	public void setAuditoriaAtributoObjeto(AuditoriaAtributoObjeto auditoriaAtributoObjeto) {
		this.auditoriaAtributoObjeto = auditoriaAtributoObjeto;
	}

}
