package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * AuditoriaAtributoObjeto generated by hbm2java
 */
@Entity
@Table(name = "auditoria_atributo_objeto", catalog = "muvitul")
public class AuditoriaAtributoObjeto implements java.io.Serializable {

	private int idBitacora;
	private AuditoriaObjeto auditoriaObjeto;
	private int idExpresion;
	private String valorNuevo;
	private Date fecha;

	public AuditoriaAtributoObjeto() {
	}

	public AuditoriaAtributoObjeto(AuditoriaObjeto auditoriaObjeto, int idExpresion, String valorNuevo, Date fecha) {
		this.auditoriaObjeto = auditoriaObjeto;
		this.idExpresion = idExpresion;
		this.valorNuevo = valorNuevo;
		this.fecha = fecha;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "auditoriaObjeto"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id_bitacora", unique = true, nullable = false)
	public int getIdBitacora() {
		return this.idBitacora;
	}

	public void setIdBitacora(int idBitacora) {
		this.idBitacora = idBitacora;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public AuditoriaObjeto getAuditoriaObjeto() {
		return this.auditoriaObjeto;
	}

	public void setAuditoriaObjeto(AuditoriaObjeto auditoriaObjeto) {
		this.auditoriaObjeto = auditoriaObjeto;
	}

	@Column(name = "id_expresion", nullable = false)
	public int getIdExpresion() {
		return this.idExpresion;
	}

	public void setIdExpresion(int idExpresion) {
		this.idExpresion = idExpresion;
	}

	@Column(name = "valor_nuevo", nullable = false, length = 100)
	public String getValorNuevo() {
		return this.valorNuevo;
	}

	public void setValorNuevo(String valorNuevo) {
		this.valorNuevo = valorNuevo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
