package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 30-abr-2017 19:07:05 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AutorizacionTaquilla generated by hbm2java
 */
@Entity
@Table(name = "autorizacion_taquilla", catalog = "muvitul")
public class AutorizacionTaquilla implements java.io.Serializable {

	private Integer idAutorizacionTaquilla;
	private TipoAutorizacion tipoAutorizacion;
	private Usuario usuario;
	private Date fecha;
	private String comentarios;

	public AutorizacionTaquilla() {
	}

	public AutorizacionTaquilla(TipoAutorizacion tipoAutorizacion, Usuario usuario, Date fecha, String comentarios) {
		this.tipoAutorizacion = tipoAutorizacion;
		this.usuario = usuario;
		this.fecha = fecha;
		this.comentarios = comentarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_autorizacion_taquilla", unique = true, nullable = false)
	public Integer getIdAutorizacionTaquilla() {
		return this.idAutorizacionTaquilla;
	}

	public void setIdAutorizacionTaquilla(Integer idAutorizacionTaquilla) {
		this.idAutorizacionTaquilla = idAutorizacionTaquilla;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_autorizacion", nullable = false)
	public TipoAutorizacion getTipoAutorizacion() {
		return this.tipoAutorizacion;
	}

	public void setTipoAutorizacion(TipoAutorizacion tipoAutorizacion) {
		this.tipoAutorizacion = tipoAutorizacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "comentarios", nullable = false, length = 250)
	public String getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

}
