package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 9/01/2017 07:06:09 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AutorizacionMovimiento generated by hbm2java
 */
@Entity
@Table(name="autorizacion_movimiento"
    ,catalog="muvitul"
)
public class AutorizacionMovimiento  implements java.io.Serializable {


     private Integer idAutorizacionMovimiento;
     private MovimientoInventario movimientoInventario;
     private Usuario usuario;
     private Date fecha;
     private String comentarios;

    public AutorizacionMovimiento() {
    }

    public AutorizacionMovimiento(MovimientoInventario movimientoInventario, Usuario usuario, Date fecha, String comentarios) {
       this.movimientoInventario = movimientoInventario;
       this.usuario = usuario;
       this.fecha = fecha;
       this.comentarios = comentarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_autorizacion_movimiento", unique=true, nullable=false)
    public Integer getIdAutorizacionMovimiento() {
        return this.idAutorizacionMovimiento;
    }
    
    public void setIdAutorizacionMovimiento(Integer idAutorizacionMovimiento) {
        this.idAutorizacionMovimiento = idAutorizacionMovimiento;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_movimiento", nullable=false)
    public MovimientoInventario getMovimientoInventario() {
        return this.movimientoInventario;
    }
    
    public void setMovimientoInventario(MovimientoInventario movimientoInventario) {
        this.movimientoInventario = movimientoInventario;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", nullable=false, length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    
    @Column(name="comentarios", nullable=false, length=250)
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }




}


