package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BoletosXTicketId generated by hbm2java
 */
@Embeddable
public class BoletosXTicketId implements java.io.Serializable {

	private int idTicket;
	private int idTipoCliente;

	public BoletosXTicketId() {
	}

	public BoletosXTicketId(int idTicket, int idTipoCliente) {
		this.idTicket = idTicket;
		this.idTipoCliente = idTipoCliente;
	}

	@Column(name = "id_ticket", nullable = false)
	public int getIdTicket() {
		return this.idTicket;
	}

	public void setIdTicket(int idTicket) {
		this.idTicket = idTicket;
	}

	@Column(name = "id_tipo_cliente", nullable = false)
	public int getIdTipoCliente() {
		return this.idTipoCliente;
	}

	public void setIdTipoCliente(int idTipoCliente) {
		this.idTipoCliente = idTipoCliente;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BoletosXTicketId))
			return false;
		BoletosXTicketId castOther = (BoletosXTicketId) other;

		return (this.getIdTicket() == castOther.getIdTicket())
				&& (this.getIdTipoCliente() == castOther.getIdTipoCliente());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdTicket();
		result = 37 * result + this.getIdTipoCliente();
		return result;
	}

}
