package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 12/02/2017 04:03:11 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BoletosXTicketId generated by hbm2java
 */
@Embeddable
public class BoletosXTicketId implements java.io.Serializable {

	private int idTicket;
	private int idFormato;

	public BoletosXTicketId() {
	}

	public BoletosXTicketId(int idTicket, int idFormato) {
		this.idTicket = idTicket;
		this.idFormato = idFormato;
	}

	@Column(name = "id_ticket", nullable = false)
	public int getIdTicket() {
		return this.idTicket;
	}

	public void setIdTicket(int idTicket) {
		this.idTicket = idTicket;
	}

	@Column(name = "id_formato", nullable = false)
	public int getIdFormato() {
		return this.idFormato;
	}

	public void setIdFormato(int idFormato) {
		this.idFormato = idFormato;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BoletosXTicketId))
			return false;
		BoletosXTicketId castOther = (BoletosXTicketId) other;

		return (this.getIdTicket() == castOther.getIdTicket()) && (this.getIdFormato() == castOther.getIdFormato());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdTicket();
		result = 37 * result + this.getIdFormato();
		return result;
	}

}
