package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 13/03/2017 10:51:10 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BoletosXTicket generated by hbm2java
 */
@Entity
@Table(name = "boletos_x_ticket", catalog = "muvitul")
public class BoletosXTicket implements java.io.Serializable {

	private BoletosXTicketId id;
	private Programacion programacion;
	private TicketVenta ticketVenta;
	private TipoCliente tipoCliente;
	private int cantidad;
	private BigDecimal importe;
	private Date fechaExhibicion;

	public BoletosXTicket() {
	}

	public BoletosXTicket(BoletosXTicketId id, Programacion programacion, TicketVenta ticketVenta,
			TipoCliente tipoCliente, int cantidad, BigDecimal importe, Date fechaExhibicion) {
		this.id = id;
		this.programacion = programacion;
		this.ticketVenta = ticketVenta;
		this.tipoCliente = tipoCliente;
		this.cantidad = cantidad;
		this.importe = importe;
		this.fechaExhibicion = fechaExhibicion;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idTicket", column = @Column(name = "id_ticket", nullable = false)),
			@AttributeOverride(name = "idTipoCliente", column = @Column(name = "id_tipo_cliente", nullable = false)) })
	public BoletosXTicketId getId() {
		return this.id;
	}

	public void setId(BoletosXTicketId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_programacion", nullable = false)
	public Programacion getProgramacion() {
		return this.programacion;
	}

	public void setProgramacion(Programacion programacion) {
		this.programacion = programacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ticket", nullable = false, insertable = false, updatable = false)
	public TicketVenta getTicketVenta() {
		return this.ticketVenta;
	}

	public void setTicketVenta(TicketVenta ticketVenta) {
		this.ticketVenta = ticketVenta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_cliente", nullable = false, insertable = false, updatable = false)
	public TipoCliente getTipoCliente() {
		return this.tipoCliente;
	}

	public void setTipoCliente(TipoCliente tipoCliente) {
		this.tipoCliente = tipoCliente;
	}

	@Column(name = "cantidad", nullable = false)
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "importe", nullable = false, precision = 15)
	public BigDecimal getImporte() {
		return this.importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_exhibicion", nullable = false, length = 10)
	public Date getFechaExhibicion() {
		return this.fechaExhibicion;
	}

	public void setFechaExhibicion(Date fechaExhibicion) {
		this.fechaExhibicion = fechaExhibicion;
	}

}
