package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 9/01/2017 07:06:09 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BoletosXTicket generated by hbm2java
 */
@Entity
@Table(name="boletos_x_ticket"
    ,catalog="muvitul"
)
public class BoletosXTicket  implements java.io.Serializable {


     private BoletosXTicketId id;
     private Formato formato;
     private TicketVenta ticketVenta;
     private int cantidad;
     private BigDecimal importe;

    public BoletosXTicket() {
    }

    public BoletosXTicket(BoletosXTicketId id, Formato formato, TicketVenta ticketVenta, int cantidad, BigDecimal importe) {
       this.id = id;
       this.formato = formato;
       this.ticketVenta = ticketVenta;
       this.cantidad = cantidad;
       this.importe = importe;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idTicket", column=@Column(name="id_ticket", nullable=false) ), 
        @AttributeOverride(name="idFormato", column=@Column(name="id_formato", nullable=false) ) } )
    public BoletosXTicketId getId() {
        return this.id;
    }
    
    public void setId(BoletosXTicketId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_formato", nullable=false, insertable=false, updatable=false)
    public Formato getFormato() {
        return this.formato;
    }
    
    public void setFormato(Formato formato) {
        this.formato = formato;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_ticket", nullable=false, insertable=false, updatable=false)
    public TicketVenta getTicketVenta() {
        return this.ticketVenta;
    }
    
    public void setTicketVenta(TicketVenta ticketVenta) {
        this.ticketVenta = ticketVenta;
    }
    
    @Column(name="cantidad", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    
    @Column(name="importe", nullable=false, precision=15)
    public BigDecimal getImporte() {
        return this.importe;
    }
    
    public void setImporte(BigDecimal importe) {
        this.importe = importe;
    }




}


