package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 9/01/2017 07:06:09 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CancelacionPago generated by hbm2java
 */
@Entity
@Table(name="cancelacion_pago"
    ,catalog="muvitul"
)
public class CancelacionPago  implements java.io.Serializable {


     private Integer idCancelacionPago;
     private Pago pago;
     private Usuario usuario;
     private MotivoCancelacion motivoCancelacion;
     private Date fecha;
     private String comentarios;

    public CancelacionPago() {
    }

    public CancelacionPago(Pago pago, Usuario usuario, MotivoCancelacion motivoCancelacion, Date fecha, String comentarios) {
       this.pago = pago;
       this.usuario = usuario;
       this.motivoCancelacion = motivoCancelacion;
       this.fecha = fecha;
       this.comentarios = comentarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_cancelacion_pago", unique=true, nullable=false)
    public Integer getIdCancelacionPago() {
        return this.idCancelacionPago;
    }
    
    public void setIdCancelacionPago(Integer idCancelacionPago) {
        this.idCancelacionPago = idCancelacionPago;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pago", nullable=false)
    public Pago getPago() {
        return this.pago;
    }
    
    public void setPago(Pago pago) {
        this.pago = pago;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_motivo_cancelacion", nullable=false)
    public MotivoCancelacion getMotivoCancelacion() {
        return this.motivoCancelacion;
    }
    
    public void setMotivoCancelacion(MotivoCancelacion motivoCancelacion) {
        this.motivoCancelacion = motivoCancelacion;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", nullable=false, length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    
    @Column(name="comentarios", nullable=false, length=250)
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }




}


