package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 12/02/2017 04:03:11 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cine generated by hbm2java
 */
@Entity
@Table(name = "cine", catalog = "muvitul")
public class Cine implements java.io.Serializable {

	private Integer idCine;
	private Contacto contacto;
	private Empresa empresa;
	private String nombre;
	private boolean activo;
	private Set<Formato> formatos = new HashSet<Formato>(0);
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);
	private Set<Promocion> promocions = new HashSet<Promocion>(0);
	private Set<Pelicula> peliculas = new HashSet<Pelicula>(0);
	private Set<MateriaPrima> materiaPrimas = new HashSet<MateriaPrima>(0);
	private Set<Sala> salas = new HashSet<Sala>(0);
	private Set<PuntoVenta> puntoVentas = new HashSet<PuntoVenta>(0);

	public Cine() {
	}

	public Cine(Contacto contacto, Empresa empresa, String nombre, boolean activo) {
		this.contacto = contacto;
		this.empresa = empresa;
		this.nombre = nombre;
		this.activo = activo;
	}

	public Cine(Contacto contacto, Empresa empresa, String nombre, boolean activo, Set<Formato> formatos,
			Set<Usuario> usuarios, Set<Promocion> promocions, Set<Pelicula> peliculas, Set<MateriaPrima> materiaPrimas,
			Set<Sala> salas, Set<PuntoVenta> puntoVentas) {
		this.contacto = contacto;
		this.empresa = empresa;
		this.nombre = nombre;
		this.activo = activo;
		this.formatos = formatos;
		this.usuarios = usuarios;
		this.promocions = promocions;
		this.peliculas = peliculas;
		this.materiaPrimas = materiaPrimas;
		this.salas = salas;
		this.puntoVentas = puntoVentas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_cine", unique = true, nullable = false)
	public Integer getIdCine() {
		return this.idCine;
	}

	public void setIdCine(Integer idCine) {
		this.idCine = idCine;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_contacto", nullable = false)
	public Contacto getContacto() {
		return this.contacto;
	}

	public void setContacto(Contacto contacto) {
		this.contacto = contacto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empresa", nullable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cine")
	public Set<Formato> getFormatos() {
		return this.formatos;
	}

	public void setFormatos(Set<Formato> formatos) {
		this.formatos = formatos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cine")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cine")
	public Set<Promocion> getPromocions() {
		return this.promocions;
	}

	public void setPromocions(Set<Promocion> promocions) {
		this.promocions = promocions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cine")
	public Set<Pelicula> getPeliculas() {
		return this.peliculas;
	}

	public void setPeliculas(Set<Pelicula> peliculas) {
		this.peliculas = peliculas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cine")
	public Set<MateriaPrima> getMateriaPrimas() {
		return this.materiaPrimas;
	}

	public void setMateriaPrimas(Set<MateriaPrima> materiaPrimas) {
		this.materiaPrimas = materiaPrimas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cine")
	public Set<Sala> getSalas() {
		return this.salas;
	}

	public void setSalas(Set<Sala> salas) {
		this.salas = salas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cine")
	public Set<PuntoVenta> getPuntoVentas() {
		return this.puntoVentas;
	}

	public void setPuntoVentas(Set<PuntoVenta> puntoVentas) {
		this.puntoVentas = puntoVentas;
	}

}
