package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClasificacionArt generated by hbm2java
 */
@Entity
@Table(name = "clasificacion_art", catalog = "muvitul")
public class ClasificacionArt implements java.io.Serializable {

	private Integer idClasificacionArt;
	private Cine cine;
	private String nombre;
	private boolean activo;
	private Set<Articulo> articulos = new HashSet<Articulo>(0);

	public ClasificacionArt() {
	}

	public ClasificacionArt(Cine cine, String nombre, boolean activo) {
		this.cine = cine;
		this.nombre = nombre;
		this.activo = activo;
	}

	public ClasificacionArt(Cine cine, String nombre, boolean activo, Set<Articulo> articulos) {
		this.cine = cine;
		this.nombre = nombre;
		this.activo = activo;
		this.articulos = articulos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_clasificacion_art", unique = true, nullable = false)
	public Integer getIdClasificacionArt() {
		return this.idClasificacionArt;
	}

	public void setIdClasificacionArt(Integer idClasificacionArt) {
		this.idClasificacionArt = idClasificacionArt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cine", nullable = false)
	public Cine getCine() {
		return this.cine;
	}

	public void setCine(Cine cine) {
		this.cine = cine;
	}

	@Column(name = "nombre", nullable = false, length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clasificacionArt")
	public Set<Articulo> getArticulos() {
		return this.articulos;
	}

	public void setArticulos(Set<Articulo> articulos) {
		this.articulos = articulos;
	}

}
