package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 13/03/2017 10:51:10 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Contacto generated by hbm2java
 */
@Entity
@Table(name = "contacto", catalog = "muvitul")
public class Contacto implements java.io.Serializable {

	private Integer idContacto;
	private Estado estado;
	private String calle;
	private String numero;
	private String colonia;
	private String cp;
	private String telefono;
	private String telefono2;
	private String correo;
	private Set<Empresa> empresas = new HashSet<Empresa>(0);
	private Set<Cine> cines = new HashSet<Cine>(0);

	public Contacto() {
	}

	public Contacto(Estado estado, String calle, String numero, String colonia, String cp, String telefono,
			String correo) {
		this.estado = estado;
		this.calle = calle;
		this.numero = numero;
		this.colonia = colonia;
		this.cp = cp;
		this.telefono = telefono;
		this.correo = correo;
	}

	public Contacto(Estado estado, String calle, String numero, String colonia, String cp, String telefono,
			String telefono2, String correo, Set<Empresa> empresas, Set<Cine> cines) {
		this.estado = estado;
		this.calle = calle;
		this.numero = numero;
		this.colonia = colonia;
		this.cp = cp;
		this.telefono = telefono;
		this.telefono2 = telefono2;
		this.correo = correo;
		this.empresas = empresas;
		this.cines = cines;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_contacto", unique = true, nullable = false)
	public Integer getIdContacto() {
		return this.idContacto;
	}

	public void setIdContacto(Integer idContacto) {
		this.idContacto = idContacto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado", nullable = false)
	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	@Column(name = "calle", nullable = false, length = 70)
	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	@Column(name = "numero", nullable = false, length = 50)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "colonia", nullable = false, length = 50)
	public String getColonia() {
		return this.colonia;
	}

	public void setColonia(String colonia) {
		this.colonia = colonia;
	}

	@Column(name = "cp", nullable = false, length = 8)
	public String getCp() {
		return this.cp;
	}

	public void setCp(String cp) {
		this.cp = cp;
	}

	@Column(name = "telefono", nullable = false, length = 15)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "telefono2", length = 15)
	public String getTelefono2() {
		return this.telefono2;
	}

	public void setTelefono2(String telefono2) {
		this.telefono2 = telefono2;
	}

	@Column(name = "correo", nullable = false, length = 45)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contacto")
	public Set<Empresa> getEmpresas() {
		return this.empresas;
	}

	public void setEmpresas(Set<Empresa> empresas) {
		this.empresas = empresas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contacto")
	public Set<Cine> getCines() {
		return this.cines;
	}

	public void setCines(Set<Cine> cines) {
		this.cines = cines;
	}

}
