package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetallePromoXPromo generated by hbm2java
 */
@Entity
@Table(name = "detalle_promo_x_promo", catalog = "muvitul")
public class DetallePromoXPromo implements java.io.Serializable {

	private DetallePromoXPromoId id;
	private DetallePromocion detallePromocion;
	private Promocion promocion;

	public DetallePromoXPromo() {
	}

	public DetallePromoXPromo(DetallePromoXPromoId id, DetallePromocion detallePromocion, Promocion promocion) {
		this.id = id;
		this.detallePromocion = detallePromocion;
		this.promocion = promocion;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idPromocion", column = @Column(name = "id_promocion", nullable = false)),
			@AttributeOverride(name = "idDetallePromocion", column = @Column(name = "id_detalle_promocion", nullable = false)) })
	public DetallePromoXPromoId getId() {
		return this.id;
	}

	public void setId(DetallePromoXPromoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_detalle_promocion", nullable = false, insertable = false, updatable = false)
	public DetallePromocion getDetallePromocion() {
		return this.detallePromocion;
	}

	public void setDetallePromocion(DetallePromocion detallePromocion) {
		this.detallePromocion = detallePromocion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_promocion", nullable = false, insertable = false, updatable = false)
	public Promocion getPromocion() {
		return this.promocion;
	}

	public void setPromocion(Promocion promocion) {
		this.promocion = promocion;
	}

}
