package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetallePromoXPromoId generated by hbm2java
 */
@Embeddable
public class DetallePromoXPromoId implements java.io.Serializable {

	private int idPromocion;
	private int idDetallePromocion;

	public DetallePromoXPromoId() {
	}

	public DetallePromoXPromoId(int idPromocion, int idDetallePromocion) {
		this.idPromocion = idPromocion;
		this.idDetallePromocion = idDetallePromocion;
	}

	@Column(name = "id_promocion", nullable = false)
	public int getIdPromocion() {
		return this.idPromocion;
	}

	public void setIdPromocion(int idPromocion) {
		this.idPromocion = idPromocion;
	}

	@Column(name = "id_detalle_promocion", nullable = false)
	public int getIdDetallePromocion() {
		return this.idDetallePromocion;
	}

	public void setIdDetallePromocion(int idDetallePromocion) {
		this.idDetallePromocion = idDetallePromocion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetallePromoXPromoId))
			return false;
		DetallePromoXPromoId castOther = (DetallePromoXPromoId) other;

		return (this.getIdPromocion() == castOther.getIdPromocion())
				&& (this.getIdDetallePromocion() == castOther.getIdDetallePromocion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPromocion();
		result = 37 * result + this.getIdDetallePromocion();
		return result;
	}

}
