package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 9/01/2017 07:06:09 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cine generated by hbm2java
 */
@Entity
@Table(name="distribuidora"
    ,catalog="muvitul"
)
public class Distribuidora  implements java.io.Serializable {


     private Integer idDistribuidora;
     private String nombre;
     private boolean activo;
     private Set<Pelicula> peliculas = new HashSet<Pelicula>(0);

    public Distribuidora() {
    }

	
    public Distribuidora(String nombre, boolean activo) {
        this.nombre = nombre;
        this.activo = activo;
    }
    public Distribuidora(String nombre, boolean activo, Set<Pelicula> peliculas) {
       this.nombre = nombre;
       this.activo = activo;
       this.peliculas = peliculas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_distribuidora", unique=true, nullable=false)
    public Integer getIdDistribuidora() {
        return this.idDistribuidora;
    }
    
    public void setIdDistribuidora(Integer idDistribuidora) {
        this.idDistribuidora = idDistribuidora;
    }
    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="activo", nullable=false)
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="distribuidora")
    public Set<Pelicula> getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Set<Pelicula> peliculas) {
        this.peliculas = peliculas;
    }

}


