package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 9/01/2017 07:06:09 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstatusPago generated by hbm2java
 */
@Entity
@Table(name="estatus_pago"
    ,catalog="muvitul"
)
public class EstatusPago  implements java.io.Serializable {


     private Integer idEstatus;
     private String nombre;
     private Set<Pago> pagos = new HashSet<Pago>(0);

    public EstatusPago() {
    }

	
    public EstatusPago(String nombre) {
        this.nombre = nombre;
    }
    public EstatusPago(String nombre, Set<Pago> pagos) {
       this.nombre = nombre;
       this.pagos = pagos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_estatus", unique=true, nullable=false)
    public Integer getIdEstatus() {
        return this.idEstatus;
    }
    
    public void setIdEstatus(Integer idEstatus) {
        this.idEstatus = idEstatus;
    }
    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estatusPago")
    public Set<Pago> getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set<Pago> pagos) {
        this.pagos = pagos;
    }




}


