package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 9/01/2017 07:06:09 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstatusUsuario generated by hbm2java
 */
@Entity
@Table(name="estatus_usuario"
    ,catalog="muvitul"
)
public class EstatusUsuario  implements java.io.Serializable {


     private Integer idEstatus;
     private String nombre;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public EstatusUsuario() {
    }

	
    public EstatusUsuario(String nombre) {
        this.nombre = nombre;
    }
    public EstatusUsuario(String nombre, Set<Usuario> usuarios) {
       this.nombre = nombre;
       this.usuarios = usuarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_estatus", unique=true, nullable=false)
    public Integer getIdEstatus() {
        return this.idEstatus;
    }
    
    public void setIdEstatus(Integer idEstatus) {
        this.idEstatus = idEstatus;
    }
    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estatusUsuario")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


