package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 12/02/2017 04:03:11 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ExistenciaMatPrima generated by hbm2java
 */
@Entity
@Table(name = "existencia_mat_prima", catalog = "muvitul")
public class ExistenciaMatPrima implements java.io.Serializable {

	private Integer idExistenciaMatPrima;
	private MateriaPrima materiaPrima;
	private long puntoReorden;
	private long existencia;

	public ExistenciaMatPrima() {
	}

	public ExistenciaMatPrima(MateriaPrima materiaPrima, long puntoReorden, long existencia) {
		this.materiaPrima = materiaPrima;
		this.puntoReorden = puntoReorden;
		this.existencia = existencia;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_existencia_mat_prima", unique = true, nullable = false)
	public Integer getIdExistenciaMatPrima() {
		return this.idExistenciaMatPrima;
	}

	public void setIdExistenciaMatPrima(Integer idExistenciaMatPrima) {
		this.idExistenciaMatPrima = idExistenciaMatPrima;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_materia_prima", nullable = false)
	public MateriaPrima getMateriaPrima() {
		return this.materiaPrima;
	}

	public void setMateriaPrima(MateriaPrima materiaPrima) {
		this.materiaPrima = materiaPrima;
	}

	@Column(name = "punto_reorden", nullable = false)
	public long getPuntoReorden() {
		return this.puntoReorden;
	}

	public void setPuntoReorden(long puntoReorden) {
		this.puntoReorden = puntoReorden;
	}

	@Column(name = "existencia", nullable = false)
	public long getExistencia() {
		return this.existencia;
	}

	public void setExistencia(long existencia) {
		this.existencia = existencia;
	}

}
