package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExistenciaBoletos generated by hbm2java
 */
@Entity
@Table(name = "existencia_boletos", catalog = "muvitul")
public class ExistenciaBoletos implements java.io.Serializable {

	private Integer idExistenciaBoletos;
	private Programacion programacion;
	private Date fechaExhibicion;
	private long boletosReservados;
	private Date fechaReserva;

	public ExistenciaBoletos() {
	}

	public ExistenciaBoletos(Programacion programacion, Date fechaExhibicion, long boletosReservados,
			Date fechaReserva) {
		this.programacion = programacion;
		this.fechaExhibicion = fechaExhibicion;
		this.boletosReservados = boletosReservados;
		this.fechaReserva = fechaReserva;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_existencia_boletos", unique = true, nullable = false)
	public Integer getIdExistenciaBoletos() {
		return this.idExistenciaBoletos;
	}

	public void setIdExistenciaBoletos(Integer idExistenciaBoletos) {
		this.idExistenciaBoletos = idExistenciaBoletos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_programacion", nullable = false)
	public Programacion getProgramacion() {
		return this.programacion;
	}

	public void setProgramacion(Programacion programacion) {
		this.programacion = programacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_exhibicion", nullable = false, length = 10)
	public Date getFechaExhibicion() {
		return this.fechaExhibicion;
	}

	public void setFechaExhibicion(Date fechaExhibicion) {
		this.fechaExhibicion = fechaExhibicion;
	}

	@Column(name = "boletos_reservados", nullable = false)
	public long getBoletosReservados() {
		return this.boletosReservados;
	}

	public void setBoletosReservados(long boletosReservados) {
		this.boletosReservados = boletosReservados;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_reserva", nullable = false, length = 19)
	public Date getFechaReserva() {
		return this.fechaReserva;
	}

	public void setFechaReserva(Date fechaReserva) {
		this.fechaReserva = fechaReserva;
	}

}
