package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ImpuestosXTicketTaquilla generated by hbm2java
 */
@Entity
@Table(name = "impuestos_x_ticket_taquilla", catalog = "muvitul")
public class ImpuestosXTicketTaquilla implements java.io.Serializable {

	private ImpuestosXTicketTaquillaId id;
	private ImpuestoBoleto impuestoBoleto;
	private TicketVenta ticketVenta;
	private BigDecimal importe;

	public ImpuestosXTicketTaquilla() {
	}

	public ImpuestosXTicketTaquilla(ImpuestosXTicketTaquillaId id, ImpuestoBoleto impuestoBoleto,
			TicketVenta ticketVenta, BigDecimal importe) {
		this.id = id;
		this.impuestoBoleto = impuestoBoleto;
		this.ticketVenta = ticketVenta;
		this.importe = importe;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idTicket", column = @Column(name = "id_ticket", nullable = false)),
			@AttributeOverride(name = "idImpuestoBoleto", column = @Column(name = "id_impuesto_boleto", nullable = false)) })
	public ImpuestosXTicketTaquillaId getId() {
		return this.id;
	}

	public void setId(ImpuestosXTicketTaquillaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_impuesto_boleto", nullable = false, insertable = false, updatable = false)
	public ImpuestoBoleto getImpuestoBoleto() {
		return this.impuestoBoleto;
	}

	public void setImpuestoBoleto(ImpuestoBoleto impuestoBoleto) {
		this.impuestoBoleto = impuestoBoleto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ticket", nullable = false, insertable = false, updatable = false)
	public TicketVenta getTicketVenta() {
		return this.ticketVenta;
	}

	public void setTicketVenta(TicketVenta ticketVenta) {
		this.ticketVenta = ticketVenta;
	}

	@Column(name = "importe", nullable = false, precision = 15)
	public BigDecimal getImporte() {
		return this.importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

}
