package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ImpuestosXTicketTaquillaId generated by hbm2java
 */
@Embeddable
public class ImpuestosXTicketTaquillaId implements java.io.Serializable {

	private int idTicket;
	private int idImpuestoBoleto;

	public ImpuestosXTicketTaquillaId() {
	}

	public ImpuestosXTicketTaquillaId(int idTicket, int idImpuestoBoleto) {
		this.idTicket = idTicket;
		this.idImpuestoBoleto = idImpuestoBoleto;
	}

	@Column(name = "id_ticket", nullable = false)
	public int getIdTicket() {
		return this.idTicket;
	}

	public void setIdTicket(int idTicket) {
		this.idTicket = idTicket;
	}

	@Column(name = "id_impuesto_boleto", nullable = false)
	public int getIdImpuestoBoleto() {
		return this.idImpuestoBoleto;
	}

	public void setIdImpuestoBoleto(int idImpuestoBoleto) {
		this.idImpuestoBoleto = idImpuestoBoleto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ImpuestosXTicketTaquillaId))
			return false;
		ImpuestosXTicketTaquillaId castOther = (ImpuestosXTicketTaquillaId) other;

		return (this.getIdTicket() == castOther.getIdTicket())
				&& (this.getIdImpuestoBoleto() == castOther.getIdImpuestoBoleto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdTicket();
		result = 37 * result + this.getIdImpuestoBoleto();
		return result;
	}

}
