package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ImpuestosXTicketProductoId generated by hbm2java
 */
@Embeddable
public class ImpuestosXTicketProductoId implements java.io.Serializable {

	private int idTicket;
	private int idImpuestoXProducto;

	public ImpuestosXTicketProductoId() {
	}

	public ImpuestosXTicketProductoId(int idTicket, int idImpuestoXProducto) {
		this.idTicket = idTicket;
		this.idImpuestoXProducto = idImpuestoXProducto;
	}

	@Column(name = "id_ticket", nullable = false)
	public int getIdTicket() {
		return this.idTicket;
	}

	public void setIdTicket(int idTicket) {
		this.idTicket = idTicket;
	}

	@Column(name = "id_impuesto_x_producto", nullable = false)
	public int getIdImpuestoXProducto() {
		return this.idImpuestoXProducto;
	}

	public void setIdImpuestoXProducto(int idImpuestoXProducto) {
		this.idImpuestoXProducto = idImpuestoXProducto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ImpuestosXTicketProductoId))
			return false;
		ImpuestosXTicketProductoId castOther = (ImpuestosXTicketProductoId) other;

		return (this.getIdTicket() == castOther.getIdTicket())
				&& (this.getIdImpuestoXProducto() == castOther.getIdImpuestoXProducto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdTicket();
		result = 37 * result + this.getIdImpuestoXProducto();
		return result;
	}

}
