package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 2/03/2017 11:59:13 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu", catalog = "muvitul")
public class Menu implements java.io.Serializable {

	private Integer idMenu;
	private Recurso recursoByIdRecurso;
	private Recurso recursoByIdRecursoPadre;

	public Menu() {
	}

	public Menu(Recurso recursoByIdRecurso, Recurso recursoByIdRecursoPadre) {
		this.recursoByIdRecurso = recursoByIdRecurso;
		this.recursoByIdRecursoPadre = recursoByIdRecursoPadre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_menu", unique = true, nullable = false)
	public Integer getIdMenu() {
		return this.idMenu;
	}

	public void setIdMenu(Integer idMenu) {
		this.idMenu = idMenu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_recurso", nullable = false)
	public Recurso getRecursoByIdRecurso() {
		return this.recursoByIdRecurso;
	}

	public void setRecursoByIdRecurso(Recurso recursoByIdRecurso) {
		this.recursoByIdRecurso = recursoByIdRecurso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_recurso_padre", nullable = false)
	public Recurso getRecursoByIdRecursoPadre() {
		return this.recursoByIdRecursoPadre;
	}

	public void setRecursoByIdRecursoPadre(Recurso recursoByIdRecursoPadre) {
		this.recursoByIdRecursoPadre = recursoByIdRecursoPadre;
	}

}
