package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 9/01/2017 07:06:09 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MovimientoInventario generated by hbm2java
 */
@Entity
@Table(name="movimiento_inventario"
    ,catalog="muvitul"
)
public class MovimientoInventario  implements java.io.Serializable {


     private Integer idMovimiento;
     private TipoMovimientoInv tipoMovimientoInv;
     private Usuario usuario;
     private MateriaPrima materiaPrima;
     private long cantidad;
     private Date fecha;
     private Set<AutorizacionMovimiento> autorizacionMovimientos = new HashSet<AutorizacionMovimiento>(0);

    public MovimientoInventario() {
    }

	
    public MovimientoInventario(TipoMovimientoInv tipoMovimientoInv, Usuario usuario, MateriaPrima materiaPrima, long cantidad, Date fecha) {
        this.tipoMovimientoInv = tipoMovimientoInv;
        this.usuario = usuario;
        this.materiaPrima = materiaPrima;
        this.cantidad = cantidad;
        this.fecha = fecha;
    }
    public MovimientoInventario(TipoMovimientoInv tipoMovimientoInv, Usuario usuario, MateriaPrima materiaPrima, long cantidad, Date fecha, Set<AutorizacionMovimiento> autorizacionMovimientos) {
       this.tipoMovimientoInv = tipoMovimientoInv;
       this.usuario = usuario;
       this.materiaPrima = materiaPrima;
       this.cantidad = cantidad;
       this.fecha = fecha;
       this.autorizacionMovimientos = autorizacionMovimientos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_movimiento", unique=true, nullable=false)
    public Integer getIdMovimiento() {
        return this.idMovimiento;
    }
    
    public void setIdMovimiento(Integer idMovimiento) {
        this.idMovimiento = idMovimiento;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_tipo_movimiento", nullable=false)
    public TipoMovimientoInv getTipoMovimientoInv() {
        return this.tipoMovimientoInv;
    }
    
    public void setTipoMovimientoInv(TipoMovimientoInv tipoMovimientoInv) {
        this.tipoMovimientoInv = tipoMovimientoInv;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_materia_prima", nullable=false)
    public MateriaPrima getMateriaPrima() {
        return this.materiaPrima;
    }
    
    public void setMateriaPrima(MateriaPrima materiaPrima) {
        this.materiaPrima = materiaPrima;
    }
    
    @Column(name="cantidad", nullable=false)
    public long getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(long cantidad) {
        this.cantidad = cantidad;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", nullable=false, length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="movimientoInventario")
    public Set<AutorizacionMovimiento> getAutorizacionMovimientos() {
        return this.autorizacionMovimientos;
    }
    
    public void setAutorizacionMovimientos(Set<AutorizacionMovimiento> autorizacionMovimientos) {
        this.autorizacionMovimientos = autorizacionMovimientos;
    }




}


