package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 2/03/2017 11:59:13 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MovimientoInventario generated by hbm2java
 */
@Entity
@Table(name = "movimiento_inventario", catalog = "muvitul")
public class MovimientoInventario implements java.io.Serializable {

	private Integer idMovimiento;
	private Articulo articulo;
	private Proveedor proveedor;
	private TipoMovimientoInv tipoMovimientoInv;
	private Usuario usuario;
	private long cantidad;
	private Date fecha;
	private BigDecimal importe;
	private String documentoRespaldo;
	private long existenciaActual;
	private Set<AutorizacionMovimiento> autorizacionMovimientos = new HashSet<AutorizacionMovimiento>(0);

	public MovimientoInventario() {
	}

	public MovimientoInventario(Articulo articulo, Proveedor proveedor, TipoMovimientoInv tipoMovimientoInv,
			Usuario usuario, long cantidad, Date fecha, BigDecimal importe, long existenciaActual) {
		this.articulo = articulo;
		this.proveedor = proveedor;
		this.tipoMovimientoInv = tipoMovimientoInv;
		this.usuario = usuario;
		this.cantidad = cantidad;
		this.fecha = fecha;
		this.importe = importe;
		this.existenciaActual = existenciaActual;
	}

	public MovimientoInventario(Articulo articulo, Proveedor proveedor, TipoMovimientoInv tipoMovimientoInv,
			Usuario usuario, long cantidad, Date fecha, BigDecimal importe, String documentoRespaldo,
			long existenciaActual, Set<AutorizacionMovimiento> autorizacionMovimientos) {
		this.articulo = articulo;
		this.proveedor = proveedor;
		this.tipoMovimientoInv = tipoMovimientoInv;
		this.usuario = usuario;
		this.cantidad = cantidad;
		this.fecha = fecha;
		this.importe = importe;
		this.documentoRespaldo = documentoRespaldo;
		this.existenciaActual = existenciaActual;
		this.autorizacionMovimientos = autorizacionMovimientos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_movimiento", unique = true, nullable = false)
	public Integer getIdMovimiento() {
		return this.idMovimiento;
	}

	public void setIdMovimiento(Integer idMovimiento) {
		this.idMovimiento = idMovimiento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_articulo", nullable = false)
	public Articulo getArticulo() {
		return this.articulo;
	}

	public void setArticulo(Articulo articulo) {
		this.articulo = articulo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_proveedor", nullable = false)
	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_movimiento", nullable = false)
	public TipoMovimientoInv getTipoMovimientoInv() {
		return this.tipoMovimientoInv;
	}

	public void setTipoMovimientoInv(TipoMovimientoInv tipoMovimientoInv) {
		this.tipoMovimientoInv = tipoMovimientoInv;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "cantidad", nullable = false)
	public long getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(long cantidad) {
		this.cantidad = cantidad;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "importe", nullable = false, precision = 15)
	public BigDecimal getImporte() {
		return this.importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

	@Column(name = "documento_respaldo", length = 20)
	public String getDocumentoRespaldo() {
		return this.documentoRespaldo;
	}

	public void setDocumentoRespaldo(String documentoRespaldo) {
		this.documentoRespaldo = documentoRespaldo;
	}

	@Column(name = "existencia_actual", nullable = false)
	public long getExistenciaActual() {
		return this.existenciaActual;
	}

	public void setExistenciaActual(long existenciaActual) {
		this.existenciaActual = existenciaActual;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movimientoInventario")
	public Set<AutorizacionMovimiento> getAutorizacionMovimientos() {
		return this.autorizacionMovimientos;
	}

	public void setAutorizacionMovimientos(Set<AutorizacionMovimiento> autorizacionMovimientos) {
		this.autorizacionMovimientos = autorizacionMovimientos;
	}

}
