package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pago generated by hbm2java
 */
@Entity
@Table(name = "pago", catalog = "muvitul")
public class Pago implements java.io.Serializable {

	private Integer idPago;
	private EstatusPago estatusPago;
	private FormaPago formaPago;
	private TicketVenta ticketVenta;
	private String noCuenta;
	private BigDecimal importe;
	private Date fecha;
	private Set<CancelacionPago> cancelacionPagos = new HashSet<CancelacionPago>(0);

	public Pago() {
	}

	public Pago(EstatusPago estatusPago, FormaPago formaPago, TicketVenta ticketVenta, BigDecimal importe, Date fecha) {
		this.estatusPago = estatusPago;
		this.formaPago = formaPago;
		this.ticketVenta = ticketVenta;
		this.importe = importe;
		this.fecha = fecha;
	}

	public Pago(EstatusPago estatusPago, FormaPago formaPago, TicketVenta ticketVenta, String noCuenta,
			BigDecimal importe, Date fecha, Set<CancelacionPago> cancelacionPagos) {
		this.estatusPago = estatusPago;
		this.formaPago = formaPago;
		this.ticketVenta = ticketVenta;
		this.noCuenta = noCuenta;
		this.importe = importe;
		this.fecha = fecha;
		this.cancelacionPagos = cancelacionPagos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_pago", unique = true, nullable = false)
	public Integer getIdPago() {
		return this.idPago;
	}

	public void setIdPago(Integer idPago) {
		this.idPago = idPago;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estatus_pago", nullable = false)
	public EstatusPago getEstatusPago() {
		return this.estatusPago;
	}

	public void setEstatusPago(EstatusPago estatusPago) {
		this.estatusPago = estatusPago;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_forma_pago", nullable = false)
	public FormaPago getFormaPago() {
		return this.formaPago;
	}

	public void setFormaPago(FormaPago formaPago) {
		this.formaPago = formaPago;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ticket", nullable = false)
	public TicketVenta getTicketVenta() {
		return this.ticketVenta;
	}

	public void setTicketVenta(TicketVenta ticketVenta) {
		this.ticketVenta = ticketVenta;
	}

	@Column(name = "no_cuenta", length = 5)
	public String getNoCuenta() {
		return this.noCuenta;
	}

	public void setNoCuenta(String noCuenta) {
		this.noCuenta = noCuenta;
	}

	@Column(name = "importe", nullable = false, precision = 15)
	public BigDecimal getImporte() {
		return this.importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pago")
	public Set<CancelacionPago> getCancelacionPagos() {
		return this.cancelacionPagos;
	}

	public void setCancelacionPagos(Set<CancelacionPago> cancelacionPagos) {
		this.cancelacionPagos = cancelacionPagos;
	}

}
