package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 9/01/2017 07:06:09 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pago generated by hbm2java
 */
@Entity
@Table(name="pago"
    ,catalog="muvitul"
)
public class Pago  implements java.io.Serializable {


     private Integer idPago;
     private FormaPago formaPago;
     private TicketVenta ticketVenta;
     private EstatusPago estatusPago;
     private String noCuenta;
     private BigDecimal importe;
     private Date fecha;
     private Set<CancelacionPago> cancelacionPagos = new HashSet<CancelacionPago>(0);

    public Pago() {
    }

	
    public Pago(FormaPago formaPago, TicketVenta ticketVenta, EstatusPago estatusPago, BigDecimal importe, Date fecha) {
        this.formaPago = formaPago;
        this.ticketVenta = ticketVenta;
        this.estatusPago = estatusPago;
        this.importe = importe;
        this.fecha = fecha;
    }
    public Pago(FormaPago formaPago, TicketVenta ticketVenta, EstatusPago estatusPago, String noCuenta, BigDecimal importe, Date fecha, Set<CancelacionPago> cancelacionPagos) {
       this.formaPago = formaPago;
       this.ticketVenta = ticketVenta;
       this.estatusPago = estatusPago;
       this.noCuenta = noCuenta;
       this.importe = importe;
       this.fecha = fecha;
       this.cancelacionPagos = cancelacionPagos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_pago", unique=true, nullable=false)
    public Integer getIdPago() {
        return this.idPago;
    }
    
    public void setIdPago(Integer idPago) {
        this.idPago = idPago;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_forma_pago", nullable=false)
    public FormaPago getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(FormaPago formaPago) {
        this.formaPago = formaPago;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_ticket", nullable=false)
    public TicketVenta getTicketVenta() {
        return this.ticketVenta;
    }
    
    public void setTicketVenta(TicketVenta ticketVenta) {
        this.ticketVenta = ticketVenta;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_estatus_pago", nullable=false)
    public EstatusPago getEstatusPago() {
        return this.estatusPago;
    }
    
    public void setEstatusPago(EstatusPago estatusPago) {
        this.estatusPago = estatusPago;
    }
    
    @Column(name="no_cuenta", length=5)
    public String getNoCuenta() {
        return this.noCuenta;
    }
    
    public void setNoCuenta(String noCuenta) {
        this.noCuenta = noCuenta;
    }
    
    @Column(name="importe", nullable=false, precision=15)
    public BigDecimal getImporte() {
        return this.importe;
    }
    
    public void setImporte(BigDecimal importe) {
        this.importe = importe;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", nullable=false, length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pago")
    public Set<CancelacionPago> getCancelacionPagos() {
        return this.cancelacionPagos;
    }
    
    public void setCancelacionPagos(Set<CancelacionPago> cancelacionPagos) {
        this.cancelacionPagos = cancelacionPagos;
    }




}


