package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name = "pais", catalog = "muvitul")
public class Pais implements java.io.Serializable {

	private Integer idPais;
	private String nombre;
	private Set<Pelicula> peliculas = new HashSet<Pelicula>(0);

	public Pais() {
	}

	public Pais(String nombre) {
		this.nombre = nombre;
	}

	public Pais(String nombre, Set<Pelicula> peliculas) {
		this.nombre = nombre;
		this.peliculas = peliculas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_pais", unique = true, nullable = false)
	public Integer getIdPais() {
		return this.idPais;
	}

	public void setIdPais(Integer idPais) {
		this.idPais = idPais;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Pelicula> getPeliculas() {
		return this.peliculas;
	}

	public void setPeliculas(Set<Pelicula> peliculas) {
		this.peliculas = peliculas;
	}

}
