package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PaquetesXPuntoVenta generated by hbm2java
 */
@Entity
@Table(name = "paquetes_x_punto_venta", catalog = "muvitul")
public class PaquetesXPuntoVenta implements java.io.Serializable {

	private PaquetesXPuntoVentaId id;
	private Paquete paquete;
	private PuntoVenta puntoVenta;

	public PaquetesXPuntoVenta() {
	}

	public PaquetesXPuntoVenta(PaquetesXPuntoVentaId id, Paquete paquete, PuntoVenta puntoVenta) {
		this.id = id;
		this.paquete = paquete;
		this.puntoVenta = puntoVenta;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idPuntoVenta", column = @Column(name = "id_punto_venta", nullable = false)),
			@AttributeOverride(name = "idPaquete", column = @Column(name = "id_paquete", nullable = false)) })
	public PaquetesXPuntoVentaId getId() {
		return this.id;
	}

	public void setId(PaquetesXPuntoVentaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_paquete", nullable = false, insertable = false, updatable = false)
	public Paquete getPaquete() {
		return this.paquete;
	}

	public void setPaquete(Paquete paquete) {
		this.paquete = paquete;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_punto_venta", nullable = false, insertable = false, updatable = false)
	public PuntoVenta getPuntoVenta() {
		return this.puntoVenta;
	}

	public void setPuntoVenta(PuntoVenta puntoVenta) {
		this.puntoVenta = puntoVenta;
	}

}
