package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 22-abr-2017 21:26:04 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Paquete generated by hbm2java
 */
@Entity
@Table(name = "paquete", catalog = "muvitul")
public class Paquete implements java.io.Serializable {

	private Integer idPaquete;
	private Cine cine;
	private String nombre;
	private byte[] icono;
	private boolean activo;
	private BigDecimal precio;
	private Set<ProductosXPaquete> productosXPaquetes = new HashSet<ProductosXPaquete>(0);
	private Set<PaquetesXPuntoVenta> paquetesXPuntoVentas = new HashSet<PaquetesXPuntoVenta>(0);
	private Set<PaquetesXTicket> paquetesXTickets = new HashSet<PaquetesXTicket>(0);

	public Paquete() {
	}

	public Paquete(Cine cine, String nombre, byte[] icono, boolean activo, BigDecimal precio) {
		this.cine = cine;
		this.nombre = nombre;
		this.icono = icono;
		this.activo = activo;
		this.precio = precio;
	}

	public Paquete(Cine cine, String nombre, byte[] icono, boolean activo, BigDecimal precio,
			Set<ProductosXPaquete> productosXPaquetes, Set<PaquetesXPuntoVenta> paquetesXPuntoVentas,
			Set<PaquetesXTicket> paquetesXTickets) {
		this.cine = cine;
		this.nombre = nombre;
		this.icono = icono;
		this.activo = activo;
		this.precio = precio;
		this.productosXPaquetes = productosXPaquetes;
		this.paquetesXPuntoVentas = paquetesXPuntoVentas;
		this.paquetesXTickets = paquetesXTickets;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_paquete", unique = true, nullable = false)
	public Integer getIdPaquete() {
		return this.idPaquete;
	}

	public void setIdPaquete(Integer idPaquete) {
		this.idPaquete = idPaquete;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_Cine", nullable = false)
	public Cine getCine() {
		return this.cine;
	}

	public void setCine(Cine cine) {
		this.cine = cine;
	}

	@Column(name = "nombre", nullable = false, length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "icono", nullable = false)
	public byte[] getIcono() {
		return this.icono;
	}

	public void setIcono(byte[] icono) {
		this.icono = icono;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "precio", nullable = false, precision = 15)
	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paquete")
	public Set<ProductosXPaquete> getProductosXPaquetes() {
		return this.productosXPaquetes;
	}

	public void setProductosXPaquetes(Set<ProductosXPaquete> productosXPaquetes) {
		this.productosXPaquetes = productosXPaquetes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paquete")
	public Set<PaquetesXPuntoVenta> getPaquetesXPuntoVentas() {
		return this.paquetesXPuntoVentas;
	}

	public void setPaquetesXPuntoVentas(Set<PaquetesXPuntoVenta> paquetesXPuntoVentas) {
		this.paquetesXPuntoVentas = paquetesXPuntoVentas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paquete")
	public Set<PaquetesXTicket> getPaquetesXTickets() {
		return this.paquetesXTickets;
	}

	public void setPaquetesXTickets(Set<PaquetesXTicket> paquetesXTickets) {
		this.paquetesXTickets = paquetesXTickets;
	}

}
