package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 9/01/2017 07:06:09 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Paquete generated by hbm2java
 */
@Entity
@Table(name="paquete"
    ,catalog="muvitul"
)
public class Paquete  implements java.io.Serializable {


     private Integer idPaquete;
     private PuntoVenta puntoVenta;
     private String nombre;
     private byte[] icono;
     private boolean activo;
     private Set<PaquetesXTicket> paquetesXTickets = new HashSet<PaquetesXTicket>(0);
     private Set<Producto> productos = new HashSet<Producto>(0);
     private Set<PrecioXPaquete> precioXPaquetes = new HashSet<PrecioXPaquete>(0);

    public Paquete() {
    }

	
    public Paquete(PuntoVenta puntoVenta, String nombre, byte[] icono, boolean activo) {
        this.puntoVenta = puntoVenta;
        this.nombre = nombre;
        this.icono = icono;
        this.activo = activo;
    }
    public Paquete(PuntoVenta puntoVenta, String nombre, byte[] icono, boolean activo, Set<PaquetesXTicket> paquetesXTickets, Set<Producto> productos, Set<PrecioXPaquete> precioXPaquetes) {
       this.puntoVenta = puntoVenta;
       this.nombre = nombre;
       this.icono = icono;
       this.activo = activo;
       this.paquetesXTickets = paquetesXTickets;
       this.productos = productos;
       this.precioXPaquetes = precioXPaquetes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_paquete", unique=true, nullable=false)
    public Integer getIdPaquete() {
        return this.idPaquete;
    }
    
    public void setIdPaquete(Integer idPaquete) {
        this.idPaquete = idPaquete;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_punto_venta", nullable=false)
    public PuntoVenta getPuntoVenta() {
        return this.puntoVenta;
    }
    
    public void setPuntoVenta(PuntoVenta puntoVenta) {
        this.puntoVenta = puntoVenta;
    }
    
    @Column(name="nombre", nullable=false, length=200)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="icono", nullable=false)
    public byte[] getIcono() {
        return this.icono;
    }
    
    public void setIcono(byte[] icono) {
        this.icono = icono;
    }
    
    @Column(name="activo", nullable=false)
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="paquete")
    public Set<PaquetesXTicket> getPaquetesXTickets() {
        return this.paquetesXTickets;
    }
    
    public void setPaquetesXTickets(Set<PaquetesXTicket> paquetesXTickets) {
        this.paquetesXTickets = paquetesXTickets;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="productos_x_paquete", catalog="muvitul", joinColumns = { 
        @JoinColumn(name="id_paquete", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="id_producto", nullable=false, updatable=false) })
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="paquete")
    public Set<PrecioXPaquete> getPrecioXPaquetes() {
        return this.precioXPaquetes;
    }
    
    public void setPrecioXPaquetes(Set<PrecioXPaquete> precioXPaquetes) {
        this.precioXPaquetes = precioXPaquetes;
    }




}


