package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PerfilesXUsuario generated by hbm2java
 */
@Entity
@Table(name = "perfiles_x_usuario", catalog = "muvitul")
public class PerfilesXUsuario implements java.io.Serializable {

	private PerfilesXUsuarioId id;
	private Perfil perfil;
	private Usuario usuario;

	public PerfilesXUsuario() {
	}

	public PerfilesXUsuario(PerfilesXUsuarioId id, Perfil perfil, Usuario usuario) {
		this.id = id;
		this.perfil = perfil;
		this.usuario = usuario;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idUsuario", column = @Column(name = "id_usuario", nullable = false)),
			@AttributeOverride(name = "idPerfil", column = @Column(name = "id_perfil", nullable = false)) })
	public PerfilesXUsuarioId getId() {
		return this.id;
	}

	public void setId(PerfilesXUsuarioId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_perfil", nullable = false, insertable = false, updatable = false)
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", nullable = false, insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
