package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PerfilesXUsuarioId generated by hbm2java
 */
@Embeddable
public class PerfilesXUsuarioId implements java.io.Serializable {

	private int idUsuario;
	private int idPerfil;

	public PerfilesXUsuarioId() {
	}

	public PerfilesXUsuarioId(int idUsuario, int idPerfil) {
		this.idUsuario = idUsuario;
		this.idPerfil = idPerfil;
	}

	@Column(name = "id_usuario", nullable = false)
	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "id_perfil", nullable = false)
	public int getIdPerfil() {
		return this.idPerfil;
	}

	public void setIdPerfil(int idPerfil) {
		this.idPerfil = idPerfil;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PerfilesXUsuarioId))
			return false;
		PerfilesXUsuarioId castOther = (PerfilesXUsuarioId) other;

		return (this.getIdUsuario() == castOther.getIdUsuario()) && (this.getIdPerfil() == castOther.getIdPerfil());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUsuario();
		result = 37 * result + this.getIdPerfil();
		return result;
	}

}
