package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "perfil", catalog = "muvitul")
public class Perfil implements java.io.Serializable {

	private Integer idPerfil;
	private String nombre;
	private Set<PerfilesXUsuario> perfilesXUsuarios = new HashSet<PerfilesXUsuario>(0);
	private Set<RecursosXPerfil> recursosXPerfils = new HashSet<RecursosXPerfil>(0);

	public Perfil() {
	}

	public Perfil(String nombre) {
		this.nombre = nombre;
	}

	public Perfil(String nombre, Set<PerfilesXUsuario> perfilesXUsuarios, Set<RecursosXPerfil> recursosXPerfils) {
		this.nombre = nombre;
		this.perfilesXUsuarios = perfilesXUsuarios;
		this.recursosXPerfils = recursosXPerfils;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_perfil", unique = true, nullable = false)
	public Integer getIdPerfil() {
		return this.idPerfil;
	}

	public void setIdPerfil(Integer idPerfil) {
		this.idPerfil = idPerfil;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set<PerfilesXUsuario> getPerfilesXUsuarios() {
		return this.perfilesXUsuarios;
	}

	public void setPerfilesXUsuarios(Set<PerfilesXUsuario> perfilesXUsuarios) {
		this.perfilesXUsuarios = perfilesXUsuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set<RecursosXPerfil> getRecursosXPerfils() {
		return this.recursosXPerfils;
	}

	public void setRecursosXPerfils(Set<RecursosXPerfil> recursosXPerfils) {
		this.recursosXPerfils = recursosXPerfils;
	}

}
