package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 13/03/2017 10:51:10 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PrecioXProducto generated by hbm2java
 */
@Entity
@Table(name = "precio_x_producto", catalog = "muvitul")
public class PrecioXProducto implements java.io.Serializable {

	private Integer idPrecioXProducto;
	private Producto producto;
	private BigDecimal precio;
	private boolean activo;

	public PrecioXProducto() {
	}

	public PrecioXProducto(Producto producto, BigDecimal precio, boolean activo) {
		this.producto = producto;
		this.precio = precio;
		this.activo = activo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_precio_x_producto", unique = true, nullable = false)
	public Integer getIdPrecioXProducto() {
		return this.idPrecioXProducto;
	}

	public void setIdPrecioXProducto(Integer idPrecioXProducto) {
		this.idPrecioXProducto = idPrecioXProducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_producto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "precio", nullable = false, precision = 15)
	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

}
