package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 12/02/2017 04:03:11 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PrecioXPaquete generated by hbm2java
 */
@Entity
@Table(name = "precio_x_paquete", catalog = "muvitul")
public class PrecioXPaquete implements java.io.Serializable {

	private Integer idPrecioXPaquete;
	private Paquete paquete;
	private BigDecimal precio;
	private boolean activo;

	public PrecioXPaquete() {
	}

	public PrecioXPaquete(Paquete paquete, BigDecimal precio, boolean activo) {
		this.paquete = paquete;
		this.precio = precio;
		this.activo = activo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_precio_x_paquete", unique = true, nullable = false)
	public Integer getIdPrecioXPaquete() {
		return this.idPrecioXPaquete;
	}

	public void setIdPrecioXPaquete(Integer idPrecioXPaquete) {
		this.idPrecioXPaquete = idPrecioXPaquete;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_paquete", nullable = false)
	public Paquete getPaquete() {
		return this.paquete;
	}

	public void setPaquete(Paquete paquete) {
		this.paquete = paquete;
	}

	@Column(name = "precio", nullable = false, precision = 15)
	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

}
