package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 9/01/2017 07:06:09 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PrecioXFormato generated by hbm2java
 */
@Entity
@Table(name="precio_x_formato"
    ,catalog="muvitul"
)
public class PrecioXFormato  implements java.io.Serializable {


     private Integer idPrecioXFormato;
     private Formato formato;
     private BigDecimal precio;
     private boolean activo;

    public PrecioXFormato() {
    }

    public PrecioXFormato(Formato formato, BigDecimal precio, boolean activo) {
       this.formato = formato;
       this.precio = precio;
       this.activo = activo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_precio_x_formato", unique=true, nullable=false)
    public Integer getIdPrecioXFormato() {
        return this.idPrecioXFormato;
    }
    
    public void setIdPrecioXFormato(Integer idPrecioXFormato) {
        this.idPrecioXFormato = idPrecioXFormato;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_formato", nullable=false)
    public Formato getFormato() {
        return this.formato;
    }
    
    public void setFormato(Formato formato) {
        this.formato = formato;
    }
    
    @Column(name="precio", nullable=false, precision=15)
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    
    @Column(name="activo", nullable=false)
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }




}


