package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 9/01/2017 07:06:09 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name="producto"
    ,catalog="muvitul"
)
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private PuntoVenta puntoVenta;
     private String nombre;
     private byte[] icono;
     private boolean activo;
     private Set<ProductosXTicket> productosXTickets = new HashSet<ProductosXTicket>(0);
     private Set<MateriaPrima> materiaPrimas = new HashSet<MateriaPrima>(0);
     private Set<Paquete> paquetes = new HashSet<Paquete>(0);
     private Set<PrecioXProducto> precioXProductos = new HashSet<PrecioXProducto>(0);

    public Producto() {
    }

	
    public Producto(PuntoVenta puntoVenta, String nombre, byte[] icono, boolean activo) {
        this.puntoVenta = puntoVenta;
        this.nombre = nombre;
        this.icono = icono;
        this.activo = activo;
    }
    public Producto(PuntoVenta puntoVenta, String nombre, byte[] icono, boolean activo, Set<ProductosXTicket> productosXTickets, Set<MateriaPrima> materiaPrimas, Set<Paquete> paquetes, Set<PrecioXProducto> precioXProductos) {
       this.puntoVenta = puntoVenta;
       this.nombre = nombre;
       this.icono = icono;
       this.activo = activo;
       this.productosXTickets = productosXTickets;
       this.materiaPrimas = materiaPrimas;
       this.paquetes = paquetes;
       this.precioXProductos = precioXProductos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_producto", unique=true, nullable=false)
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_punto_venta", nullable=false)
    public PuntoVenta getPuntoVenta() {
        return this.puntoVenta;
    }
    
    public void setPuntoVenta(PuntoVenta puntoVenta) {
        this.puntoVenta = puntoVenta;
    }
    
    @Column(name="nombre", nullable=false, length=200)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="icono", nullable=false)
    public byte[] getIcono() {
        return this.icono;
    }
    
    public void setIcono(byte[] icono) {
        this.icono = icono;
    }
    
    @Column(name="activo", nullable=false)
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="producto")
    public Set<ProductosXTicket> getProductosXTickets() {
        return this.productosXTickets;
    }
    
    public void setProductosXTickets(Set<ProductosXTicket> productosXTickets) {
        this.productosXTickets = productosXTickets;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="materias_primas_x_producto", catalog="muvitul", joinColumns = { 
        @JoinColumn(name="id_producto", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="id_materia_prima", nullable=false, updatable=false) })
    public Set<MateriaPrima> getMateriaPrimas() {
        return this.materiaPrimas;
    }
    
    public void setMateriaPrimas(Set<MateriaPrima> materiaPrimas) {
        this.materiaPrimas = materiaPrimas;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="productos")
    public Set<Paquete> getPaquetes() {
        return this.paquetes;
    }
    
    public void setPaquetes(Set<Paquete> paquetes) {
        this.paquetes = paquetes;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="producto")
    public Set<PrecioXProducto> getPrecioXProductos() {
        return this.precioXProductos;
    }
    
    public void setPrecioXProductos(Set<PrecioXProducto> precioXProductos) {
        this.precioXProductos = precioXProductos;
    }




}


