package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductosXPaquete generated by hbm2java
 */
@Entity
@Table(name = "productos_x_paquete", catalog = "muvitul")
public class ProductosXPaquete implements java.io.Serializable {

	private ProductosXPaqueteId id;
	private Paquete paquete;
	private Producto producto;
	private long cantidad;

	public ProductosXPaquete() {
	}

	public ProductosXPaquete(ProductosXPaqueteId id, Paquete paquete, Producto producto, long cantidad) {
		this.id = id;
		this.paquete = paquete;
		this.producto = producto;
		this.cantidad = cantidad;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idPaquete", column = @Column(name = "id_paquete", nullable = false)),
			@AttributeOverride(name = "idProducto", column = @Column(name = "id_producto", nullable = false)) })
	public ProductosXPaqueteId getId() {
		return this.id;
	}

	public void setId(ProductosXPaqueteId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_paquete", nullable = false, insertable = false, updatable = false)
	public Paquete getPaquete() {
		return this.paquete;
	}

	public void setPaquete(Paquete paquete) {
		this.paquete = paquete;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_producto", nullable = false, insertable = false, updatable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "cantidad", nullable = false)
	public long getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(long cantidad) {
		this.cantidad = cantidad;
	}

}
