package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 9/01/2017 07:06:09 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Programacion generated by hbm2java
 */
@Entity
@Table(name="programacion"
    ,catalog="muvitul"
)
public class Programacion  implements java.io.Serializable {


     private Integer idProgramacion;
     private Formato formato;
     private Version version;
         private Sala sala;
     private Pelicula pelicula;
     private String diaSemana;
     private Date horario;

    public Programacion() {
    }

    public Programacion(Formato formato, Sala sala, Pelicula pelicula, String diaSemana, Date horario) {
       this.formato = formato;
       this.sala = sala;
       this.pelicula = pelicula;
       this.diaSemana = diaSemana;
       this.horario = horario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_programacion", unique=true, nullable=false)
    public Integer getIdProgramacion() {
        return this.idProgramacion;
    }
    
    public void setIdProgramacion(Integer idProgramacion) {
        this.idProgramacion = idProgramacion;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_formato", nullable=false)
    public Formato getFormato() {
        return this.formato;
    }
    
    public void setFormato(Formato formato) {
        this.formato = formato;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_version", nullable=false)
    public Version getVersion() {
        return this.version;
    }
    
    public void setVersion(Version version) {
        this.version = version;
    }
    
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sala", nullable=false)
    public Sala getSala() {
        return this.sala;
    }
    
    public void setSala(Sala sala) {
        this.sala = sala;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pelicula", nullable=false)
    public Pelicula getPelicula() {
        return this.pelicula;
    }
    
    public void setPelicula(Pelicula pelicula) {
        this.pelicula = pelicula;
    }
    
    @Column(name="dia_semana", nullable=false, length=1)
    public String getDiaSemana() {
        return this.diaSemana;
    }
    
    public void setDiaSemana(String diaSemana) {
        this.diaSemana = diaSemana;
    }
    @Temporal(TemporalType.TIME)
    @Column(name="horario", nullable=false, length=8)
    public Date getHorario() {
        return this.horario;
    }
    
    public void setHorario(Date horario) {
        this.horario = horario;
    }




}


