package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 2/03/2017 11:59:13 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Programacion generated by hbm2java
 */
@Entity
@Table(name = "programacion", catalog = "muvitul")
public class Programacion implements java.io.Serializable {

	private Integer idProgramacion;
	private Formato formato;
	private Pelicula pelicula;
	private Sala sala;
	private Version version;
	private String diaSemana;
	private Date horario;
	private Date fechaVigencia;
	private Set<ExistenciaBoletos> existenciaBoletoses = new HashSet<ExistenciaBoletos>(0);
	private Set<BoletosXTicket> boletosXTickets = new HashSet<BoletosXTicket>(0);

	public Programacion() {
	}

	public Programacion(Formato formato, Pelicula pelicula, Sala sala, Version version, String diaSemana, Date horario,
			Date fechaVigencia) {
		this.formato = formato;
		this.pelicula = pelicula;
		this.sala = sala;
		this.version = version;
		this.diaSemana = diaSemana;
		this.horario = horario;
		this.fechaVigencia = fechaVigencia;
	}

	public Programacion(Formato formato, Pelicula pelicula, Sala sala, Version version, String diaSemana, Date horario,
			Date fechaVigencia, Set<ExistenciaBoletos> existenciaBoletoses, Set<BoletosXTicket> boletosXTickets) {
		this.formato = formato;
		this.pelicula = pelicula;
		this.sala = sala;
		this.version = version;
		this.diaSemana = diaSemana;
		this.horario = horario;
		this.fechaVigencia = fechaVigencia;
		this.existenciaBoletoses = existenciaBoletoses;
		this.boletosXTickets = boletosXTickets;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_programacion", unique = true, nullable = false)
	public Integer getIdProgramacion() {
		return this.idProgramacion;
	}

	public void setIdProgramacion(Integer idProgramacion) {
		this.idProgramacion = idProgramacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_formato", nullable = false)
	public Formato getFormato() {
		return this.formato;
	}

	public void setFormato(Formato formato) {
		this.formato = formato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pelicula", nullable = false)
	public Pelicula getPelicula() {
		return this.pelicula;
	}

	public void setPelicula(Pelicula pelicula) {
		this.pelicula = pelicula;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sala", nullable = false)
	public Sala getSala() {
		return this.sala;
	}

	public void setSala(Sala sala) {
		this.sala = sala;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_version", nullable = false)
	public Version getVersion() {
		return this.version;
	}

	public void setVersion(Version version) {
		this.version = version;
	}

	@Column(name = "dia_semana", nullable = false, length = 2)
	public String getDiaSemana() {
		return this.diaSemana;
	}

	public void setDiaSemana(String diaSemana) {
		this.diaSemana = diaSemana;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horario", nullable = false, length = 8)
	public Date getHorario() {
		return this.horario;
	}

	public void setHorario(Date horario) {
		this.horario = horario;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_vigencia", nullable = false, length = 10)
	public Date getFechaVigencia() {
		return this.fechaVigencia;
	}

	public void setFechaVigencia(Date fechaVigencia) {
		this.fechaVigencia = fechaVigencia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "programacion")
	public Set<ExistenciaBoletos> getExistenciaBoletoses() {
		return this.existenciaBoletoses;
	}

	public void setExistenciaBoletoses(Set<ExistenciaBoletos> existenciaBoletoses) {
		this.existenciaBoletoses = existenciaBoletoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "programacion")
	public Set<BoletosXTicket> getBoletosXTickets() {
		return this.boletosXTickets;
	}

	public void setBoletosXTickets(Set<BoletosXTicket> boletosXTickets) {
		this.boletosXTickets = boletosXTickets;
	}

}
