package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 9/01/2017 07:06:09 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Promocion generated by hbm2java
 */
@Entity
@Table(name="promocion"
    ,catalog="muvitul"
)
public class Promocion  implements java.io.Serializable {


     private Integer idPromocion;
     private TipoPromocion tipoPromocion;
     private int nombre;
     private Date fechaInicio;
     private Date fechaFin;
     private BigDecimal importe;
     private boolean activo;
     private Set<PromocionesXTicket> promocionesXTickets = new HashSet<PromocionesXTicket>(0);

    public Promocion() {
    }

	
    public Promocion(TipoPromocion tipoPromocion, int nombre, Date fechaInicio, Date fechaFin, BigDecimal importe, boolean activo) {
        this.tipoPromocion = tipoPromocion;
        this.nombre = nombre;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.importe = importe;
        this.activo = activo;
    }
    public Promocion(TipoPromocion tipoPromocion, int nombre, Date fechaInicio, Date fechaFin, BigDecimal importe, boolean activo, Set<PromocionesXTicket> promocionesXTickets) {
       this.tipoPromocion = tipoPromocion;
       this.nombre = nombre;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.importe = importe;
       this.activo = activo;
       this.promocionesXTickets = promocionesXTickets;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_promocion", unique=true, nullable=false)
    public Integer getIdPromocion() {
        return this.idPromocion;
    }
    
    public void setIdPromocion(Integer idPromocion) {
        this.idPromocion = idPromocion;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_tipo_promocion", nullable=false)
    public TipoPromocion getTipoPromocion() {
        return this.tipoPromocion;
    }
    
    public void setTipoPromocion(TipoPromocion tipoPromocion) {
        this.tipoPromocion = tipoPromocion;
    }
    
    @Column(name="nombre", nullable=false)
    public int getNombre() {
        return this.nombre;
    }
    
    public void setNombre(int nombre) {
        this.nombre = nombre;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_inicio", nullable=false, length=19)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_fin", nullable=false, length=19)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    
    @Column(name="importe", nullable=false, precision=15)
    public BigDecimal getImporte() {
        return this.importe;
    }
    
    public void setImporte(BigDecimal importe) {
        this.importe = importe;
    }
    
    @Column(name="activo", nullable=false)
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="promocion")
    public Set<PromocionesXTicket> getPromocionesXTickets() {
        return this.promocionesXTickets;
    }
    
    public void setPromocionesXTickets(Set<PromocionesXTicket> promocionesXTickets) {
        this.promocionesXTickets = promocionesXTickets;
    }




}


