package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 24-abr-2017 22:02:25 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PromocionPara generated by hbm2java
 */
@Entity
@Table(name = "promocion_para", catalog = "muvitul")
public class PromocionPara implements java.io.Serializable {

	private Integer idPromocionPara;
	private String nombre;
	private String clave;
	private Set<Promocion> promocions = new HashSet<Promocion>(0);

	public PromocionPara() {
	}

	public PromocionPara(String nombre, String clave) {
		this.nombre = nombre;
		this.clave = clave;
	}

	public PromocionPara(String nombre, String clave, Set<Promocion> promocions) {
		this.nombre = nombre;
		this.clave = clave;
		this.promocions = promocions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_promocion_para", unique = true, nullable = false)
	public Integer getIdPromocionPara() {
		return this.idPromocionPara;
	}

	public void setIdPromocionPara(Integer idPromocionPara) {
		this.idPromocionPara = idPromocionPara;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "clave", nullable = false, length = 25)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "promocionPara")
	public Set<Promocion> getPromocions() {
		return this.promocions;
	}

	public void setPromocions(Set<Promocion> promocions) {
		this.promocions = promocions;
	}

}
