package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 12/02/2017 04:03:11 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PuntoVenta generated by hbm2java
 */
@Entity
@Table(name = "punto_venta", catalog = "muvitul")
public class PuntoVenta implements java.io.Serializable {

	private Integer idPuntoVenta;
	private Cine cine;
	private TipoPuntoVenta tipoPuntoVenta;
	private String nombre;
	private Set<Paquete> paquetes = new HashSet<Paquete>(0);
	private Set<TicketVenta> ticketVentas = new HashSet<TicketVenta>(0);
	private Set<Producto> productos = new HashSet<Producto>(0);

	public PuntoVenta() {
	}

	public PuntoVenta(Cine cine, TipoPuntoVenta tipoPuntoVenta, String nombre) {
		this.cine = cine;
		this.tipoPuntoVenta = tipoPuntoVenta;
		this.nombre = nombre;
	}

	public PuntoVenta(Cine cine, TipoPuntoVenta tipoPuntoVenta, String nombre, Set<Paquete> paquetes,
			Set<TicketVenta> ticketVentas, Set<Producto> productos) {
		this.cine = cine;
		this.tipoPuntoVenta = tipoPuntoVenta;
		this.nombre = nombre;
		this.paquetes = paquetes;
		this.ticketVentas = ticketVentas;
		this.productos = productos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_punto_venta", unique = true, nullable = false)
	public Integer getIdPuntoVenta() {
		return this.idPuntoVenta;
	}

	public void setIdPuntoVenta(Integer idPuntoVenta) {
		this.idPuntoVenta = idPuntoVenta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cine", nullable = false)
	public Cine getCine() {
		return this.cine;
	}

	public void setCine(Cine cine) {
		this.cine = cine;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_punto_venta", nullable = false)
	public TipoPuntoVenta getTipoPuntoVenta() {
		return this.tipoPuntoVenta;
	}

	public void setTipoPuntoVenta(TipoPuntoVenta tipoPuntoVenta) {
		this.tipoPuntoVenta = tipoPuntoVenta;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "puntoVenta")
	public Set<Paquete> getPaquetes() {
		return this.paquetes;
	}

	public void setPaquetes(Set<Paquete> paquetes) {
		this.paquetes = paquetes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "puntoVenta")
	public Set<TicketVenta> getTicketVentas() {
		return this.ticketVentas;
	}

	public void setTicketVentas(Set<TicketVenta> ticketVentas) {
		this.ticketVentas = ticketVentas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "puntoVenta")
	public Set<Producto> getProductos() {
		return this.productos;
	}

	public void setProductos(Set<Producto> productos) {
		this.productos = productos;
	}

}
