package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RecursosXPerfilId generated by hbm2java
 */
@Embeddable
public class RecursosXPerfilId implements java.io.Serializable {

	private int idPerfil;
	private int idRecurso;

	public RecursosXPerfilId() {
	}

	public RecursosXPerfilId(int idPerfil, int idRecurso) {
		this.idPerfil = idPerfil;
		this.idRecurso = idRecurso;
	}

	@Column(name = "id_perfil", nullable = false)
	public int getIdPerfil() {
		return this.idPerfil;
	}

	public void setIdPerfil(int idPerfil) {
		this.idPerfil = idPerfil;
	}

	@Column(name = "id_recurso", nullable = false)
	public int getIdRecurso() {
		return this.idRecurso;
	}

	public void setIdRecurso(int idRecurso) {
		this.idRecurso = idRecurso;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RecursosXPerfilId))
			return false;
		RecursosXPerfilId castOther = (RecursosXPerfilId) other;

		return (this.getIdPerfil() == castOther.getIdPerfil()) && (this.getIdRecurso() == castOther.getIdRecurso());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPerfil();
		result = 37 * result + this.getIdRecurso();
		return result;
	}

}
