package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Recurso generated by hbm2java
 */
@Entity
@Table(name = "recurso", catalog = "muvitul")
public class Recurso implements java.io.Serializable {

	private Integer idRecurso;
	private String nombre;
	private String recursoUrl;
	private boolean activo;
	private boolean permitirATodos;
	private Set<Menu> menusForIdRecurso = new HashSet<Menu>(0);
	private Set<Menu> menusForIdRecursoPadre = new HashSet<Menu>(0);
	private Set<RecursosXPerfil> recursosXPerfils = new HashSet<RecursosXPerfil>(0);

	public Recurso() {
	}

	public Recurso(String nombre, String recursoUrl, boolean activo, boolean permitirATodos) {
		this.nombre = nombre;
		this.recursoUrl = recursoUrl;
		this.activo = activo;
		this.permitirATodos = permitirATodos;
	}

	public Recurso(String nombre, String recursoUrl, boolean activo, boolean permitirATodos,
			Set<Menu> menusForIdRecurso, Set<Menu> menusForIdRecursoPadre, Set<RecursosXPerfil> recursosXPerfils) {
		this.nombre = nombre;
		this.recursoUrl = recursoUrl;
		this.activo = activo;
		this.permitirATodos = permitirATodos;
		this.menusForIdRecurso = menusForIdRecurso;
		this.menusForIdRecursoPadre = menusForIdRecursoPadre;
		this.recursosXPerfils = recursosXPerfils;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_recurso", unique = true, nullable = false)
	public Integer getIdRecurso() {
		return this.idRecurso;
	}

	public void setIdRecurso(Integer idRecurso) {
		this.idRecurso = idRecurso;
	}

	@Column(name = "nombre", nullable = false, length = 70)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "recurso_url", nullable = false, length = 200)
	public String getRecursoUrl() {
		return this.recursoUrl;
	}

	public void setRecursoUrl(String recursoUrl) {
		this.recursoUrl = recursoUrl;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "permitir_a_todos", nullable = false)
	public boolean isPermitirATodos() {
		return this.permitirATodos;
	}

	public void setPermitirATodos(boolean permitirATodos) {
		this.permitirATodos = permitirATodos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "recursoByIdRecurso")
	public Set<Menu> getMenusForIdRecurso() {
		return this.menusForIdRecurso;
	}

	public void setMenusForIdRecurso(Set<Menu> menusForIdRecurso) {
		this.menusForIdRecurso = menusForIdRecurso;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "recursoByIdRecursoPadre")
	public Set<Menu> getMenusForIdRecursoPadre() {
		return this.menusForIdRecursoPadre;
	}

	public void setMenusForIdRecursoPadre(Set<Menu> menusForIdRecursoPadre) {
		this.menusForIdRecursoPadre = menusForIdRecursoPadre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "recurso")
	public Set<RecursosXPerfil> getRecursosXPerfils() {
		return this.recursosXPerfils;
	}

	public void setRecursosXPerfils(Set<RecursosXPerfil> recursosXPerfils) {
		this.recursosXPerfils = recursosXPerfils;
	}

}
