package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 9/01/2017 07:06:09 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Recurso generated by hbm2java
 */
@Entity
@Table(name="recurso"
    ,catalog="muvitul"
)
public class Recurso  implements java.io.Serializable {


     private Integer idRecurso;
     private String nombre;
     private String recursoUrl;
     private boolean activo;
     private boolean permitirATodos;
     private Set<Menu> menusForIdRecursoPadre = new HashSet<Menu>(0);
     private Set<Menu> menusForIdRecurso = new HashSet<Menu>(0);
     private Set<Perfil> perfils = new HashSet<Perfil>(0);

    public Recurso() {
    }

	
    public Recurso(String nombre, String recursoUrl, boolean activo, boolean permitirATodos) {
        this.nombre = nombre;
        this.recursoUrl = recursoUrl;
        this.activo = activo;
        this.permitirATodos = permitirATodos;
    }
    public Recurso(String nombre, String recursoUrl, boolean activo, boolean permitirATodos, Set<Menu> menusForIdRecursoPadre, Set<Menu> menusForIdRecurso, Set<Perfil> perfils) {
       this.nombre = nombre;
       this.recursoUrl = recursoUrl;
       this.activo = activo;
       this.permitirATodos = permitirATodos;
       this.menusForIdRecursoPadre = menusForIdRecursoPadre;
       this.menusForIdRecurso = menusForIdRecurso;
       this.perfils = perfils;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_recurso", unique=true, nullable=false)
    public Integer getIdRecurso() {
        return this.idRecurso;
    }
    
    public void setIdRecurso(Integer idRecurso) {
        this.idRecurso = idRecurso;
    }
    
    @Column(name="nombre", nullable=false, length=70)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="recurso_url", nullable=false, length=200)
    public String getRecursoUrl() {
        return this.recursoUrl;
    }
    
    public void setRecursoUrl(String recursoUrl) {
        this.recursoUrl = recursoUrl;
    }
    
    @Column(name="activo", nullable=false)
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    
    @Column(name="permitir_a_todos", nullable=false)
    public boolean isPermitirATodos() {
        return this.permitirATodos;
    }
    
    public void setPermitirATodos(boolean permitirATodos) {
        this.permitirATodos = permitirATodos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="recursoByIdRecursoPadre")
    public Set<Menu> getMenusForIdRecursoPadre() {
        return this.menusForIdRecursoPadre;
    }
    
    public void setMenusForIdRecursoPadre(Set<Menu> menusForIdRecursoPadre) {
        this.menusForIdRecursoPadre = menusForIdRecursoPadre;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="recursoByIdRecurso")
    public Set<Menu> getMenusForIdRecurso() {
        return this.menusForIdRecurso;
    }
    
    public void setMenusForIdRecurso(Set<Menu> menusForIdRecurso) {
        this.menusForIdRecurso = menusForIdRecurso;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="recursos")
    public Set<Perfil> getPerfils() {
        return this.perfils;
    }
    
    public void setPerfils(Set<Perfil> perfils) {
        this.perfils = perfils;
    }




}


