package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RecursosXPerfil generated by hbm2java
 */
@Entity
@Table(name = "recursos_x_perfil", catalog = "muvitul")
public class RecursosXPerfil implements java.io.Serializable {

	private RecursosXPerfilId id;
	private Perfil perfil;
	private Recurso recurso;

	public RecursosXPerfil() {
	}

	public RecursosXPerfil(RecursosXPerfilId id, Perfil perfil, Recurso recurso) {
		this.id = id;
		this.perfil = perfil;
		this.recurso = recurso;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idPerfil", column = @Column(name = "id_perfil", nullable = false)),
			@AttributeOverride(name = "idRecurso", column = @Column(name = "id_recurso", nullable = false)) })
	public RecursosXPerfilId getId() {
		return this.id;
	}

	public void setId(RecursosXPerfilId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_perfil", nullable = false, insertable = false, updatable = false)
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_recurso", nullable = false, insertable = false, updatable = false)
	public Recurso getRecurso() {
		return this.recurso;
	}

	public void setRecurso(Recurso recurso) {
		this.recurso = recurso;
	}

}
