package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Regalo generated by hbm2java
 */
@Entity
@Table(name = "regalo", catalog = "muvitul")
public class Regalo implements java.io.Serializable {

	private Integer idRegalo;
	private Cine cine;
	private String nombre;
	private String descripcion;
	private Set<DetallePromocion> detallePromocions = new HashSet<DetallePromocion>(0);

	public Regalo() {
	}

	public Regalo(Cine cine, String nombre, String descripcion) {
		this.cine = cine;
		this.nombre = nombre;
		this.descripcion = descripcion;
	}

	public Regalo(Cine cine, String nombre, String descripcion, Set<DetallePromocion> detallePromocions) {
		this.cine = cine;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.detallePromocions = detallePromocions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_regalo", unique = true, nullable = false)
	public Integer getIdRegalo() {
		return this.idRegalo;
	}

	public void setIdRegalo(Integer idRegalo) {
		this.idRegalo = idRegalo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cine", nullable = false)
	public Cine getCine() {
		return this.cine;
	}

	public void setCine(Cine cine) {
		this.cine = cine;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", nullable = false, length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "regalo")
	public Set<DetallePromocion> getDetallePromocions() {
		return this.detallePromocions;
	}

	public void setDetallePromocions(Set<DetallePromocion> detallePromocions) {
		this.detallePromocions = detallePromocions;
	}

}
