package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 9/01/2017 07:06:09 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TicketVenta generated by hbm2java
 */
@Entity
@Table(name="ticket_venta"
    ,catalog="muvitul"
)
public class TicketVenta  implements java.io.Serializable {


     private Integer idTicket;
     private PuntoVenta puntoVenta;
     private Usuario usuario;
     private Date fecha;
     private BigDecimal descuento;
     private BigDecimal importe;
     private BigDecimal iva;
     private BigDecimal total;
     private Set<PromocionesXTicket> promocionesXTickets = new HashSet<PromocionesXTicket>(0);
     private Set<BoletosXTicket> boletosXTickets = new HashSet<BoletosXTicket>(0);
     private Set<PaquetesXTicket> paquetesXTickets = new HashSet<PaquetesXTicket>(0);
     private Set<Pago> pagos = new HashSet<Pago>(0);
     private Set<ProductosXTicket> productosXTickets = new HashSet<ProductosXTicket>(0);

    public TicketVenta() {
    }

	
    public TicketVenta(PuntoVenta puntoVenta, Usuario usuario, Date fecha, BigDecimal descuento, BigDecimal importe, BigDecimal iva, BigDecimal total) {
        this.puntoVenta = puntoVenta;
        this.usuario = usuario;
        this.fecha = fecha;
        this.descuento = descuento;
        this.importe = importe;
        this.iva = iva;
        this.total = total;
    }
    public TicketVenta(PuntoVenta puntoVenta, Usuario usuario, Date fecha, BigDecimal descuento, BigDecimal importe, BigDecimal iva, BigDecimal total, Set<PromocionesXTicket> promocionesXTickets, Set<BoletosXTicket> boletosXTickets, Set<PaquetesXTicket> paquetesXTickets, Set<Pago> pagos, Set<ProductosXTicket> productosXTickets) {
       this.puntoVenta = puntoVenta;
       this.usuario = usuario;
       this.fecha = fecha;
       this.descuento = descuento;
       this.importe = importe;
       this.iva = iva;
       this.total = total;
       this.promocionesXTickets = promocionesXTickets;
       this.boletosXTickets = boletosXTickets;
       this.paquetesXTickets = paquetesXTickets;
       this.pagos = pagos;
       this.productosXTickets = productosXTickets;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_ticket", unique=true, nullable=false)
    public Integer getIdTicket() {
        return this.idTicket;
    }
    
    public void setIdTicket(Integer idTicket) {
        this.idTicket = idTicket;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_punto_venta", nullable=false)
    public PuntoVenta getPuntoVenta() {
        return this.puntoVenta;
    }
    
    public void setPuntoVenta(PuntoVenta puntoVenta) {
        this.puntoVenta = puntoVenta;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", nullable=false, length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    
    @Column(name="descuento", nullable=false, precision=15)
    public BigDecimal getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(BigDecimal descuento) {
        this.descuento = descuento;
    }
    
    @Column(name="importe", nullable=false, precision=15)
    public BigDecimal getImporte() {
        return this.importe;
    }
    
    public void setImporte(BigDecimal importe) {
        this.importe = importe;
    }
    
    @Column(name="iva", nullable=false, precision=15)
    public BigDecimal getIva() {
        return this.iva;
    }
    
    public void setIva(BigDecimal iva) {
        this.iva = iva;
    }
    
    @Column(name="total", nullable=false, precision=15)
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="ticketVenta")
    public Set<PromocionesXTicket> getPromocionesXTickets() {
        return this.promocionesXTickets;
    }
    
    public void setPromocionesXTickets(Set<PromocionesXTicket> promocionesXTickets) {
        this.promocionesXTickets = promocionesXTickets;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="ticketVenta")
    public Set<BoletosXTicket> getBoletosXTickets() {
        return this.boletosXTickets;
    }
    
    public void setBoletosXTickets(Set<BoletosXTicket> boletosXTickets) {
        this.boletosXTickets = boletosXTickets;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="ticketVenta")
    public Set<PaquetesXTicket> getPaquetesXTickets() {
        return this.paquetesXTickets;
    }
    
    public void setPaquetesXTickets(Set<PaquetesXTicket> paquetesXTickets) {
        this.paquetesXTickets = paquetesXTickets;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="ticketVenta")
    public Set<Pago> getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set<Pago> pagos) {
        this.pagos = pagos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="ticketVenta")
    public Set<ProductosXTicket> getProductosXTickets() {
        return this.productosXTickets;
    }
    
    public void setProductosXTickets(Set<ProductosXTicket> productosXTickets) {
        this.productosXTickets = productosXTickets;
    }




}


