package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 30-abr-2017 19:07:05 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoAutorizacion generated by hbm2java
 */
@Entity
@Table(name = "tipo_autorizacion", catalog = "muvitul")
public class TipoAutorizacion implements java.io.Serializable {

	private Integer idTipoAutorizacion;
	private String nombre;
	private boolean activo;
	private Set<AutorizacionTaquilla> autorizacionTaquillas = new HashSet<AutorizacionTaquilla>(0);

	public TipoAutorizacion() {
	}

	public TipoAutorizacion(String nombre, boolean activo) {
		this.nombre = nombre;
		this.activo = activo;
	}

	public TipoAutorizacion(String nombre, boolean activo, Set<AutorizacionTaquilla> autorizacionTaquillas) {
		this.nombre = nombre;
		this.activo = activo;
		this.autorizacionTaquillas = autorizacionTaquillas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_tipo_autorizacion", unique = true, nullable = false)
	public Integer getIdTipoAutorizacion() {
		return this.idTipoAutorizacion;
	}

	public void setIdTipoAutorizacion(Integer idTipoAutorizacion) {
		this.idTipoAutorizacion = idTipoAutorizacion;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoAutorizacion")
	public Set<AutorizacionTaquilla> getAutorizacionTaquillas() {
		return this.autorizacionTaquillas;
	}

	public void setAutorizacionTaquillas(Set<AutorizacionTaquilla> autorizacionTaquillas) {
		this.autorizacionTaquillas = autorizacionTaquillas;
	}

}
