package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 22-abr-2017 21:26:04 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoPromocion generated by hbm2java
 */
@Entity
@Table(name = "tipo_promocion", catalog = "muvitul")
public class TipoPromocion implements java.io.Serializable {

	private Integer idTipoPromocion;
	private String nombre;
	private String descripcion;
	private String clave;
	private Set<Promocion> promocions = new HashSet<Promocion>(0);

	public TipoPromocion() {
	}

	public TipoPromocion(String nombre, String descripcion, String clave) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.clave = clave;
	}

	public TipoPromocion(String nombre, String descripcion, String clave, Set<Promocion> promocions) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.clave = clave;
		this.promocions = promocions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_tipo_promocion", unique = true, nullable = false)
	public Integer getIdTipoPromocion() {
		return this.idTipoPromocion;
	}

	public void setIdTipoPromocion(Integer idTipoPromocion) {
		this.idTipoPromocion = idTipoPromocion;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", nullable = false, length = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "clave", nullable = false, length = 25)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoPromocion")
	public Set<Promocion> getPromocions() {
		return this.promocions;
	}

	public void setPromocions(Set<Promocion> promocions) {
		this.promocions = promocions;
	}

}
