package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 13/03/2017 10:51:10 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoAutorizacionMov generated by hbm2java
 */
@Entity
@Table(name = "tipo_autorizacion_mov", catalog = "muvitul")
public class TipoAutorizacionMov implements java.io.Serializable {

	private int idTipoAutorizacionMov;
	private int nombre;
	private int activo;
	private Set<AutorizacionMovimiento> autorizacionMovimientos = new HashSet<AutorizacionMovimiento>(0);

	public TipoAutorizacionMov() {
	}

	public TipoAutorizacionMov(int idTipoAutorizacionMov, int nombre, int activo) {
		this.idTipoAutorizacionMov = idTipoAutorizacionMov;
		this.nombre = nombre;
		this.activo = activo;
	}

	public TipoAutorizacionMov(int idTipoAutorizacionMov, int nombre, int activo,
			Set<AutorizacionMovimiento> autorizacionMovimientos) {
		this.idTipoAutorizacionMov = idTipoAutorizacionMov;
		this.nombre = nombre;
		this.activo = activo;
		this.autorizacionMovimientos = autorizacionMovimientos;
	}

	@Id

	@Column(name = "id_tipo_autorizacion_mov", unique = true, nullable = false)
	public int getIdTipoAutorizacionMov() {
		return this.idTipoAutorizacionMov;
	}

	public void setIdTipoAutorizacionMov(int idTipoAutorizacionMov) {
		this.idTipoAutorizacionMov = idTipoAutorizacionMov;
	}

	@Column(name = "nombre", nullable = false)
	public int getNombre() {
		return this.nombre;
	}

	public void setNombre(int nombre) {
		this.nombre = nombre;
	}

	@Column(name = "activo", nullable = false)
	public int getActivo() {
		return this.activo;
	}

	public void setActivo(int activo) {
		this.activo = activo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoAutorizacionMov")
	public Set<AutorizacionMovimiento> getAutorizacionMovimientos() {
		return this.autorizacionMovimientos;
	}

	public void setAutorizacionMovimientos(Set<AutorizacionMovimiento> autorizacionMovimientos) {
		this.autorizacionMovimientos = autorizacionMovimientos;
	}

}
