package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UnidadMedida generated by hbm2java
 */
@Entity
@Table(name = "unidad_medida", catalog = "muvitul")
public class UnidadMedida implements java.io.Serializable {

	private Integer idUnidadMedida;
	private String nombre;
	private boolean activo;
	private Set<Articulo> articulos = new HashSet<Articulo>(0);

	public UnidadMedida() {
	}

	public UnidadMedida(String nombre, boolean activo) {
		this.nombre = nombre;
		this.activo = activo;
	}

	public UnidadMedida(String nombre, boolean activo, Set<Articulo> articulos) {
		this.nombre = nombre;
		this.activo = activo;
		this.articulos = articulos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_unidad_medida", unique = true, nullable = false)
	public Integer getIdUnidadMedida() {
		return this.idUnidadMedida;
	}

	public void setIdUnidadMedida(Integer idUnidadMedida) {
		this.idUnidadMedida = idUnidadMedida;
	}

	@Column(name = "nombre", nullable = false, length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unidadMedida")
	public Set<Articulo> getArticulos() {
		return this.articulos;
	}

	public void setArticulos(Set<Articulo> articulos) {
		this.articulos = articulos;
	}

}
