package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Version generated by hbm2java
 */
@Entity
@Table(name = "version", catalog = "muvitul")
public class Version implements java.io.Serializable {

	private Integer idVersion;
	private String nombre;
	private boolean activo;
	private Set<Programacion> programacions = new HashSet<Programacion>(0);

	public Version() {
	}

	public Version(String nombre, boolean activo) {
		this.nombre = nombre;
		this.activo = activo;
	}

	public Version(String nombre, boolean activo, Set<Programacion> programacions) {
		this.nombre = nombre;
		this.activo = activo;
		this.programacions = programacions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_version", unique = true, nullable = false)
	public Integer getIdVersion() {
		return this.idVersion;
	}

	public void setIdVersion(Integer idVersion) {
		this.idVersion = idVersion;
	}

	@Column(name = "nombre", nullable = false, length = 35)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "version")
	public Set<Programacion> getProgramacions() {
		return this.programacions;
	}

	public void setProgramacions(Set<Programacion> programacions) {
		this.programacions = programacions;
	}

}
